"""Export publication macros from saved host-timing evidence, without retiming."""
from __future__ import annotations

import argparse
import csv
from decimal import Decimal
import hashlib
import json
from pathlib import Path
import re

STUDY = Path(__file__).resolve().parent
PAPER = STUDY.parents[1]
TARGET = PAPER / "latex/beta_timing_metrics.tex"


def number(value: str | int | Decimal) -> str:
    return format(Decimal(value).normalize(), "f")


def tex_text(value: str) -> str:
    replacements = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
                    "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
                    "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    return "".join(replacements.get(c, c) for c in value)


def render() -> str:
    results = STUDY / "results"
    environment = json.loads((results / "environment.json").read_text(encoding="utf-8"))
    matlab = json.loads((results / "matlab_environment.json").read_text(encoding="utf-8"))
    # Avoid attaching old timings to changed algorithm or benchmark sources.
    for relative, expected in environment["source_sha256"].items():
        source = PAPER / relative.replace("\\", "/")
        if hashlib.sha256(source.read_bytes()).hexdigest() != expected:
            raise ValueError(f"Timing evidence is stale for {source}; rerun the study")
    with (results / "summary.csv").open(newline="", encoding="utf-8") as f:
        rows = {(r["implementation"], r["scenario"], r["measurement"]): r for r in csv.DictReader(f)}

    def p95(name: str, scenario: str = "mixed_100", measurement: str = "individual") -> Decimal:
        row = rows[name, scenario, measurement]
        expected_samples = environment["individual_samples_per_scenario" if measurement == "individual"
                                       else "batch_samples_per_scenario"]
        expected_calls = 1 if measurement == "individual" else environment["calls_per_batch"]
        if int(row["samples"]) != expected_samples or int(row["calls_per_sample"]) != expected_calls:
            raise ValueError(f"Inconsistent timing counts for {name}")
        value = Decimal(row["p95_ns"])
        if not value.is_finite() or value < 0:
            raise ValueError(f"Invalid p95 for {name}")
        return value

    cpp_floor = p95("cpp_timer_only", "baseline")
    if any(p95(name) != cpp_floor for name in ("cpp_double_beta_only", "cpp_double_conditioner")):
        raise ValueError("C++ p95 no longer equals timer baseline; revise the manuscript interpretation")
    if not all(flag in environment["compile_command"] for flag in ("-O3", "-fno-lto")):
        raise ValueError("Compiler flags differ from the manuscript method")
    compiler_line = environment["compiler_version"].splitlines()[0]
    compiler_version = re.search(r"(\d+\.\d+\.\d+)\s*$", compiler_line)
    if "g++" not in compiler_line or compiler_version is None:
        raise ValueError("Compiler is not the GCC version described by the manuscript")
    cpu = environment["cpu"]
    if not isinstance(cpu, dict) or not cpu.get("Name"):
        raise ValueError("No CPU model available for publication")
    values = {
        "BetaTimingCpu": tex_text(cpu["Name"].strip()),
        "BetaTimingMatlabRelease": tex_text(matlab["release"]),
        "BetaTimingGccVersion": compiler_version.group(1),
        "BetaTimingWarmupCalls": number(environment["warmup_calls"]),
        "BetaTimingIndividualSamples": number(environment["individual_samples_per_scenario"]),
        "BetaTimingBatchSamples": number(environment["batch_samples_per_scenario"]),
        "BetaTimingBatchSize": number(environment["calls_per_batch"]),
        "BetaTimingInputCount": number(matlab["verified_article_inputs"]),
        "BetaTimingMatlabBetaPninetyfiveUs": number(p95("matlab_beta_only") / 1000),
        "BetaTimingMatlabFullPninetyfiveUs": number(p95("matlab_existing_conditioner") / 1000),
        "BetaTimingMatlabActiveBetaPninetyfiveUs": number(p95("matlab_beta_only", "conditioned_3") / 1000),
        "BetaTimingMatlabActiveFullPninetyfiveUs": number(p95("matlab_existing_conditioner", "conditioned_3") / 1000),
        "BetaTimingCppTimerFloorUs": number(cpp_floor / 1000),
        "BetaTimingCppBetaBatchPninetyfiveNs": number(p95("cpp_double_beta_only", measurement="batch_mean")),
        "BetaTimingCppFullBatchPninetyfiveNs": number(p95("cpp_double_conditioner", measurement="batch_mean")),
    }
    header = ["% Generated by studies/beta-timing/export_latex.py; do not edit.",
              "% Source: studies/beta-timing/results/summary.csv and environment metadata.",
              "% Individual-call p95 and p95 of batch-average costs are distinct statistics.",
              "% summary.csv SHA256: " + hashlib.sha256((results / "summary.csv").read_bytes()).hexdigest()]
    return "\n".join(header + [rf"\newcommand{{\{name}}}{{{value}}}" for name, value in values.items()]) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check saved macros without changing them")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            raise SystemExit("Publication timing macros are stale; run export_latex.py")
        print("PASS: publication timing macros match saved evidence")
    else:
        TARGET.write_text(text, encoding="utf-8")
        print(f"Exported {TARGET}")


if __name__ == "__main__":
    main()
