version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
     - bun run dev

  build:
    aliases: ["b"]
    cmds:
     - bun run build
     - go build -o webserver.exe ./go_server/server.go