version: '3'

tasks:

  default:
    deps: [m]

  main:
    aliases: [m]
    cmds:
     - bun run dev

  build:
    aliases: [b]
    cmds:
     - bun run build
     - go build -o webserver.exe ./go_server/server.go

  play:
    aliases: [p]
    cmds:
     - bun run play/play.ts
