version: '3'

tasks:

  default:
    deps: [ps]

  main:
    cmds:
     - uv run calibracao.py

  plot:
    aliases: [p]
    cmds:
     - uv run grafico.py

  plot_series:
    aliases: [ps]
    cmds:
     - uv run grafico_timeseries.py
