/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/messaging.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Telemetry, Telemetry, AUTO)


PB_BIND(AnalogStatus, AnalogStatus, AUTO)


PB_BIND(SystemStatus, SystemStatus, AUTO)


PB_BIND(LogMessage, LogMessage, AUTO)


PB_BIND(OtaStatus, OtaStatus, AUTO)


PB_BIND(OtaBegin, OtaBegin, AUTO)


PB_BIND(OtaChunk, OtaChunk, 2)


PB_BIND(OtaEnd, OtaEnd, AUTO)


PB_BIND(OtaCommand, OtaCommand, 2)


PB_BIND(UiCommand, UiCommand, 2)


PB_BIND(UiCommandResult, UiCommandResult, 2)


PB_BIND(AnalogDiagnosticResult, AnalogDiagnosticResult, AUTO)


PB_BIND(BlePacket, BlePacket, 2)

















