/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_MESSAGING_PB_H_INCLUDED
#define PB_PROTO_MESSAGING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _BleSignalSet {
    BleSignalSet_BLE_SET_A = 0,
    BleSignalSet_BLE_SET_B = 1
} BleSignalSet;

typedef enum _BleAnalogReadState {
    BleAnalogReadState_BLE_READ_IDLE = 0,
    BleAnalogReadState_BLE_READING = 1,
    BleAnalogReadState_BLE_READ_DISABLED = 2
} BleAnalogReadState;

typedef enum _BleSignalState {
    BleSignalState_BLE_SIG_IDLE = 0,
    BleSignalState_BLE_SIG_RUNNING = 1
} BleSignalState;

typedef enum _BleControlState {
    BleControlState_BLE_CTRL_OFF = 0,
    BleControlState_BLE_CTRL_ON = 1
} BleControlState;

typedef enum _BleLedMode {
    BleLedMode_LED_NORMAL = 0,
    BleLedMode_LED_BLINKING = 1
} BleLedMode;

typedef enum _BleLogLevel {
    BleLogLevel_BLE_LOG_INFO = 0,
    BleLogLevel_BLE_LOG_WARN = 1,
    BleLogLevel_BLE_LOG_ERROR = 2
} BleLogLevel;

/* OTA Communication */
typedef enum _OtaState {
    OtaState_OTA_IDLE = 0,
    OtaState_OTA_DOWNLOADING = 1,
    OtaState_OTA_VERIFYING = 2,
    OtaState_OTA_FINISHED = 3,
    OtaState_OTA_ERROR = 4
} OtaState;

/* Struct definitions */
/* Telemetry message containing analog port readings */
typedef struct _Telemetry {
    float an3;
    float an5;
    float an6;
    uint32_t timestamp_ms;
} Telemetry;

typedef struct _AnalogStatus {
    uint32_t seq;
    bool valid;
    uint64_t timestamp_us;
    uint32_t age_us;
    uint32_t target_triples_per_cycle;
    uint32_t measured_triples_per_second;
    uint32_t raw_an3;
    uint32_t raw_an5;
    uint32_t raw_an6;
    float calibrated_an3;
    float calibrated_an5;
    float calibrated_an6;
    uint32_t latency_min_us;
    uint32_t latency_avg_us;
    uint32_t latency_p95_us;
    uint32_t latency_max_us;
    uint32_t overflow_count;
    uint32_t miss_count;
    uint32_t consecutive_misses;
    uint32_t fault_code;
    uint32_t acquisition_mode;
    uint32_t samples_read;
    uint32_t samples_rejected;
    uint32_t channel_order_anomalies;
    uint32_t partial_triples;
    uint32_t frame_drops;
    uint32_t pool_flushes;
    bool calibration_lut_ready;
    /* Smallest measurement age the acquisition pipeline can deliver
 (frame accumulation + scheduling margin). */
    uint32_t min_snapshot_age_us;
    /* Effective control-point age budget: active dataset cycle window,
 clamped to min_snapshot_age_us. */
    uint32_t control_max_age_us;
    /* Times a frame timestamp fell back to read time because the ISR
 timestamp ring was empty or desynchronized. */
    uint32_t frame_ts_fallbacks;
} AnalogStatus;

/* System status message */
typedef struct _SystemStatus {
    BleSignalSet active_set;
    BleSignalState signal_state;
    BleAnalogReadState ble_read_state;
    BleControlState control_state;
    float alpha;
    bool has_alpha;
    bool matrix_a_valid;
    bool matrix_b_valid;
    uint32_t current_cycles;
    uint32_t total_cycles;
    uint32_t monitor_ms;
    uint32_t dead_time_us;
    BleLedMode led_mode;
    bool ble_congested;
    uint32_t adc_min;
    uint32_t adc_max;
    uint32_t adc_avg;
    uint32_t dead_time_tail_overhead_cycles;
    bool has_analog;
    AnalogStatus analog;
    uint32_t signal_edge_overhead_up_cycles;
    uint32_t signal_edge_overhead_down_cycles;
} SystemStatus;

/* General purpose log message */
typedef struct _LogMessage {
    BleLogLevel level;
    char text[128];
} LogMessage;

typedef struct _OtaStatus {
    OtaState state;
    uint32_t progress_percent;
    char message[64];
    uint32_t written_size;
    uint32_t expected_seq;
} OtaStatus;

typedef struct _OtaBegin {
    uint32_t file_size;
} OtaBegin;

typedef PB_BYTES_ARRAY_T(512) OtaChunk_data_t;
typedef struct _OtaChunk {
    uint32_t seq;
    OtaChunk_data_t data;
} OtaChunk;

typedef struct _OtaEnd {
    char sha256[64];
} OtaEnd;

typedef struct _OtaCommand {
    pb_size_t which_type;
    union {
        OtaBegin begin;
        OtaChunk chunk;
        OtaEnd end;
        bool abort;
    } type;
} OtaCommand;

/* Extensible UI command envelope.
 The command name is namespaced (for example "signal.start") and the payload
 is command-owned JSON so new lab commands can be added without changing this
 schema every time. */
typedef struct _UiCommand {
    char name[64];
    char json[384];
    uint32_t request_id;
} UiCommand;

typedef struct _UiCommandResult {
    uint32_t request_id;
    char name[64];
    bool ok;
    char code[32];
    char message[128];
    char json[512];
} UiCommandResult;

typedef struct _AnalogDiagnosticResult {
    bool valid;
    bool running;
    uint32_t duration_ms;
    uint64_t elapsed_us;
    uint32_t seq_delta;
    uint32_t miss_delta;
    uint32_t overflow_delta;
    uint32_t seq;
    uint32_t age_us;
    uint32_t rate_tps;
    uint32_t raw_an3;
    uint32_t raw_an5;
    uint32_t raw_an6;
    float cal_an3;
    float cal_an5;
    float cal_an6;
    uint32_t latency_avg_us;
    uint32_t latency_p95_us;
    uint32_t fault_code;
    uint32_t timing_samples;
    float playback_avg_us;
    float loop_us;
    uint32_t overruns;
    uint32_t timing_faults;
    char message[96];
} AnalogDiagnosticResult;

typedef struct _AnalogConfigCaseResult {
    uint32_t sample_hz;
    uint32_t duration_ms;
    uint64_t elapsed_us;
    uint32_t seq_delta;
    uint32_t rate_tps;
    uint32_t age_us;
    uint32_t miss_delta;
    uint32_t overflow_delta;
    uint32_t fault_code;
    uint32_t latency_avg_us;
    uint32_t latency_p95_us;
    uint32_t playback_avg_us_x100;
    uint32_t loop_us_x100;
    uint32_t overruns_delta;
    uint32_t timing_faults_delta;
    uint32_t dma_samples_delta;
    uint32_t dma_anomalies_delta;
} AnalogConfigCaseResult;

/* Short, bounded sweep result for comparing ADC DMA sample-rate settings over
 BLE without streaming logs from the firmware task. */
typedef struct _AnalogConfigTestResult {
    bool valid;
    bool running;
    uint32_t case_count;
    pb_size_t cases_count;
    AnalogConfigCaseResult cases[4];
    char message[96];
} AnalogConfigTestResult;

/* Top-level message for BLE communication */
typedef struct _BlePacket {
    pb_size_t which_payload;
    union {
        Telemetry telemetry;
        SystemStatus status;
        LogMessage log;
        OtaStatus ota_status;
        UiCommandResult command_result;
        AnalogDiagnosticResult analog_diagnostic_result;
        AnalogConfigTestResult analog_config_test_result;
    } payload;
} BlePacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _BleSignalSet_MIN BleSignalSet_BLE_SET_A
#define _BleSignalSet_MAX BleSignalSet_BLE_SET_B
#define _BleSignalSet_ARRAYSIZE ((BleSignalSet)(BleSignalSet_BLE_SET_B+1))

#define _BleAnalogReadState_MIN BleAnalogReadState_BLE_READ_IDLE
#define _BleAnalogReadState_MAX BleAnalogReadState_BLE_READ_DISABLED
#define _BleAnalogReadState_ARRAYSIZE ((BleAnalogReadState)(BleAnalogReadState_BLE_READ_DISABLED+1))

#define _BleSignalState_MIN BleSignalState_BLE_SIG_IDLE
#define _BleSignalState_MAX BleSignalState_BLE_SIG_RUNNING
#define _BleSignalState_ARRAYSIZE ((BleSignalState)(BleSignalState_BLE_SIG_RUNNING+1))

#define _BleControlState_MIN BleControlState_BLE_CTRL_OFF
#define _BleControlState_MAX BleControlState_BLE_CTRL_ON
#define _BleControlState_ARRAYSIZE ((BleControlState)(BleControlState_BLE_CTRL_ON+1))

#define _BleLedMode_MIN BleLedMode_LED_NORMAL
#define _BleLedMode_MAX BleLedMode_LED_BLINKING
#define _BleLedMode_ARRAYSIZE ((BleLedMode)(BleLedMode_LED_BLINKING+1))

#define _BleLogLevel_MIN BleLogLevel_BLE_LOG_INFO
#define _BleLogLevel_MAX BleLogLevel_BLE_LOG_ERROR
#define _BleLogLevel_ARRAYSIZE ((BleLogLevel)(BleLogLevel_BLE_LOG_ERROR+1))

#define _OtaState_MIN OtaState_OTA_IDLE
#define _OtaState_MAX OtaState_OTA_ERROR
#define _OtaState_ARRAYSIZE ((OtaState)(OtaState_OTA_ERROR+1))



#define SystemStatus_active_set_ENUMTYPE BleSignalSet
#define SystemStatus_signal_state_ENUMTYPE BleSignalState
#define SystemStatus_ble_read_state_ENUMTYPE BleAnalogReadState
#define SystemStatus_control_state_ENUMTYPE BleControlState
#define SystemStatus_led_mode_ENUMTYPE BleLedMode

#define LogMessage_level_ENUMTYPE BleLogLevel

#define OtaStatus_state_ENUMTYPE OtaState












/* Initializer values for message structs */
#define Telemetry_init_default                   {0, 0, 0, 0}
#define AnalogStatus_init_default                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SystemStatus_init_default                {_BleSignalSet_MIN, _BleSignalState_MIN, _BleAnalogReadState_MIN, _BleControlState_MIN, 0, 0, 0, 0, 0, 0, 0, 0, _BleLedMode_MIN, 0, 0, 0, 0, 0, false, AnalogStatus_init_default, 0, 0}
#define LogMessage_init_default                  {_BleLogLevel_MIN, ""}
#define OtaStatus_init_default                   {_OtaState_MIN, 0, "", 0, 0}
#define OtaBegin_init_default                    {0}
#define OtaChunk_init_default                    {0, {0, {0}}}
#define OtaEnd_init_default                      {""}
#define OtaCommand_init_default                  {0, {OtaBegin_init_default}}
#define UiCommand_init_default                   {"", "", 0}
#define UiCommandResult_init_default             {0, "", 0, "", "", ""}
#define AnalogDiagnosticResult_init_default      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ""}
#define AnalogConfigCaseResult_init_default      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AnalogConfigTestResult_init_default      {0, 0, 0, 0, {AnalogConfigCaseResult_init_default, AnalogConfigCaseResult_init_default, AnalogConfigCaseResult_init_default, AnalogConfigCaseResult_init_default}, ""}
#define BlePacket_init_default                   {0, {Telemetry_init_default}}
#define Telemetry_init_zero                      {0, 0, 0, 0}
#define AnalogStatus_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SystemStatus_init_zero                   {_BleSignalSet_MIN, _BleSignalState_MIN, _BleAnalogReadState_MIN, _BleControlState_MIN, 0, 0, 0, 0, 0, 0, 0, 0, _BleLedMode_MIN, 0, 0, 0, 0, 0, false, AnalogStatus_init_zero, 0, 0}
#define LogMessage_init_zero                     {_BleLogLevel_MIN, ""}
#define OtaStatus_init_zero                      {_OtaState_MIN, 0, "", 0, 0}
#define OtaBegin_init_zero                       {0}
#define OtaChunk_init_zero                       {0, {0, {0}}}
#define OtaEnd_init_zero                         {""}
#define OtaCommand_init_zero                     {0, {OtaBegin_init_zero}}
#define UiCommand_init_zero                      {"", "", 0}
#define UiCommandResult_init_zero                {0, "", 0, "", "", ""}
#define AnalogDiagnosticResult_init_zero         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ""}
#define AnalogConfigCaseResult_init_zero         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define AnalogConfigTestResult_init_zero         {0, 0, 0, 0, {AnalogConfigCaseResult_init_zero, AnalogConfigCaseResult_init_zero, AnalogConfigCaseResult_init_zero, AnalogConfigCaseResult_init_zero}, ""}
#define BlePacket_init_zero                      {0, {Telemetry_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Telemetry_an3_tag                        1
#define Telemetry_an5_tag                        2
#define Telemetry_an6_tag                        3
#define Telemetry_timestamp_ms_tag               4
#define AnalogStatus_seq_tag                     1
#define AnalogStatus_valid_tag                   2
#define AnalogStatus_timestamp_us_tag            3
#define AnalogStatus_age_us_tag                  4
#define AnalogStatus_target_triples_per_cycle_tag 5
#define AnalogStatus_measured_triples_per_second_tag 6
#define AnalogStatus_raw_an3_tag                 7
#define AnalogStatus_raw_an5_tag                 8
#define AnalogStatus_raw_an6_tag                 9
#define AnalogStatus_calibrated_an3_tag          10
#define AnalogStatus_calibrated_an5_tag          11
#define AnalogStatus_calibrated_an6_tag          12
#define AnalogStatus_latency_min_us_tag          13
#define AnalogStatus_latency_avg_us_tag          14
#define AnalogStatus_latency_p95_us_tag          15
#define AnalogStatus_latency_max_us_tag          16
#define AnalogStatus_overflow_count_tag          17
#define AnalogStatus_miss_count_tag              18
#define AnalogStatus_consecutive_misses_tag      19
#define AnalogStatus_fault_code_tag              20
#define AnalogStatus_acquisition_mode_tag        21
#define AnalogStatus_samples_read_tag            22
#define AnalogStatus_samples_rejected_tag        23
#define AnalogStatus_channel_order_anomalies_tag 24
#define AnalogStatus_partial_triples_tag         25
#define AnalogStatus_frame_drops_tag             26
#define AnalogStatus_pool_flushes_tag            27
#define AnalogStatus_calibration_lut_ready_tag   28
#define AnalogStatus_min_snapshot_age_us_tag     29
#define AnalogStatus_control_max_age_us_tag      30
#define AnalogStatus_frame_ts_fallbacks_tag      31
#define SystemStatus_active_set_tag              1
#define SystemStatus_signal_state_tag            2
#define SystemStatus_ble_read_state_tag          3
#define SystemStatus_control_state_tag           4
#define SystemStatus_alpha_tag                   5
#define SystemStatus_has_alpha_tag               6
#define SystemStatus_matrix_a_valid_tag          7
#define SystemStatus_matrix_b_valid_tag          8
#define SystemStatus_current_cycles_tag          9
#define SystemStatus_total_cycles_tag            10
#define SystemStatus_monitor_ms_tag              11
#define SystemStatus_dead_time_us_tag            12
#define SystemStatus_led_mode_tag                14
#define SystemStatus_ble_congested_tag           15
#define SystemStatus_adc_min_tag                 16
#define SystemStatus_adc_max_tag                 17
#define SystemStatus_adc_avg_tag                 18
#define SystemStatus_dead_time_tail_overhead_cycles_tag 19
#define SystemStatus_analog_tag                  20
#define SystemStatus_signal_edge_overhead_up_cycles_tag 22
#define SystemStatus_signal_edge_overhead_down_cycles_tag 23
#define LogMessage_level_tag                     1
#define LogMessage_text_tag                      2
#define OtaStatus_state_tag                      1
#define OtaStatus_progress_percent_tag           2
#define OtaStatus_message_tag                    3
#define OtaStatus_written_size_tag               4
#define OtaStatus_expected_seq_tag               5
#define OtaBegin_file_size_tag                   1
#define OtaChunk_seq_tag                         1
#define OtaChunk_data_tag                        2
#define OtaEnd_sha256_tag                        1
#define OtaCommand_begin_tag                     1
#define OtaCommand_chunk_tag                     2
#define OtaCommand_end_tag                       3
#define OtaCommand_abort_tag                     4
#define UiCommand_name_tag                       1
#define UiCommand_json_tag                       2
#define UiCommand_request_id_tag                 3
#define UiCommandResult_request_id_tag           1
#define UiCommandResult_name_tag                 2
#define UiCommandResult_ok_tag                   3
#define UiCommandResult_code_tag                 4
#define UiCommandResult_message_tag              5
#define UiCommandResult_json_tag                 6
#define AnalogDiagnosticResult_valid_tag         1
#define AnalogDiagnosticResult_running_tag       2
#define AnalogDiagnosticResult_duration_ms_tag   3
#define AnalogDiagnosticResult_elapsed_us_tag    4
#define AnalogDiagnosticResult_seq_delta_tag     5
#define AnalogDiagnosticResult_miss_delta_tag    6
#define AnalogDiagnosticResult_overflow_delta_tag 7
#define AnalogDiagnosticResult_seq_tag           8
#define AnalogDiagnosticResult_age_us_tag        9
#define AnalogDiagnosticResult_rate_tps_tag      10
#define AnalogDiagnosticResult_raw_an3_tag       11
#define AnalogDiagnosticResult_raw_an5_tag       12
#define AnalogDiagnosticResult_raw_an6_tag       13
#define AnalogDiagnosticResult_cal_an3_tag       14
#define AnalogDiagnosticResult_cal_an5_tag       15
#define AnalogDiagnosticResult_cal_an6_tag       16
#define AnalogDiagnosticResult_latency_avg_us_tag 17
#define AnalogDiagnosticResult_latency_p95_us_tag 18
#define AnalogDiagnosticResult_fault_code_tag    19
#define AnalogDiagnosticResult_timing_samples_tag 20
#define AnalogDiagnosticResult_playback_avg_us_tag 21
#define AnalogDiagnosticResult_loop_us_tag       22
#define AnalogDiagnosticResult_overruns_tag      23
#define AnalogDiagnosticResult_timing_faults_tag 24
#define AnalogDiagnosticResult_message_tag       25
#define AnalogConfigCaseResult_sample_hz_tag     1
#define AnalogConfigCaseResult_duration_ms_tag   2
#define AnalogConfigCaseResult_elapsed_us_tag    3
#define AnalogConfigCaseResult_seq_delta_tag     4
#define AnalogConfigCaseResult_rate_tps_tag      5
#define AnalogConfigCaseResult_age_us_tag        6
#define AnalogConfigCaseResult_miss_delta_tag    7
#define AnalogConfigCaseResult_overflow_delta_tag 8
#define AnalogConfigCaseResult_fault_code_tag    9
#define AnalogConfigCaseResult_latency_avg_us_tag 10
#define AnalogConfigCaseResult_latency_p95_us_tag 11
#define AnalogConfigCaseResult_playback_avg_us_x100_tag 12
#define AnalogConfigCaseResult_loop_us_x100_tag  13
#define AnalogConfigCaseResult_overruns_delta_tag 14
#define AnalogConfigCaseResult_timing_faults_delta_tag 15
#define AnalogConfigCaseResult_dma_samples_delta_tag 16
#define AnalogConfigCaseResult_dma_anomalies_delta_tag 17
#define AnalogConfigTestResult_valid_tag         1
#define AnalogConfigTestResult_running_tag       2
#define AnalogConfigTestResult_case_count_tag    3
#define AnalogConfigTestResult_cases_tag         4
#define AnalogConfigTestResult_message_tag       5
#define BlePacket_telemetry_tag                  1
#define BlePacket_status_tag                     2
#define BlePacket_log_tag                        3
#define BlePacket_ota_status_tag                 4
#define BlePacket_command_result_tag             5
#define BlePacket_analog_diagnostic_result_tag   6
#define BlePacket_analog_config_test_result_tag  7

/* Struct field encoding specification for nanopb */
#define Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    an3,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    an5,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    an6,               3) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      4)
#define Telemetry_CALLBACK NULL
#define Telemetry_DEFAULT NULL

#define AnalogStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   SINGULAR, BOOL,     valid,             2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      3) \
X(a, STATIC,   SINGULAR, UINT32,   age_us,            4) \
X(a, STATIC,   SINGULAR, UINT32,   target_triples_per_cycle,   5) \
X(a, STATIC,   SINGULAR, UINT32,   measured_triples_per_second,   6) \
X(a, STATIC,   SINGULAR, UINT32,   raw_an3,           7) \
X(a, STATIC,   SINGULAR, UINT32,   raw_an5,           8) \
X(a, STATIC,   SINGULAR, UINT32,   raw_an6,           9) \
X(a, STATIC,   SINGULAR, FLOAT,    calibrated_an3,   10) \
X(a, STATIC,   SINGULAR, FLOAT,    calibrated_an5,   11) \
X(a, STATIC,   SINGULAR, FLOAT,    calibrated_an6,   12) \
X(a, STATIC,   SINGULAR, UINT32,   latency_min_us,   13) \
X(a, STATIC,   SINGULAR, UINT32,   latency_avg_us,   14) \
X(a, STATIC,   SINGULAR, UINT32,   latency_p95_us,   15) \
X(a, STATIC,   SINGULAR, UINT32,   latency_max_us,   16) \
X(a, STATIC,   SINGULAR, UINT32,   overflow_count,   17) \
X(a, STATIC,   SINGULAR, UINT32,   miss_count,       18) \
X(a, STATIC,   SINGULAR, UINT32,   consecutive_misses,  19) \
X(a, STATIC,   SINGULAR, UINT32,   fault_code,       20) \
X(a, STATIC,   SINGULAR, UINT32,   acquisition_mode,  21) \
X(a, STATIC,   SINGULAR, UINT32,   samples_read,     22) \
X(a, STATIC,   SINGULAR, UINT32,   samples_rejected,  23) \
X(a, STATIC,   SINGULAR, UINT32,   channel_order_anomalies,  24) \
X(a, STATIC,   SINGULAR, UINT32,   partial_triples,  25) \
X(a, STATIC,   SINGULAR, UINT32,   frame_drops,      26) \
X(a, STATIC,   SINGULAR, UINT32,   pool_flushes,     27) \
X(a, STATIC,   SINGULAR, BOOL,     calibration_lut_ready,  28) \
X(a, STATIC,   SINGULAR, UINT32,   min_snapshot_age_us,  29) \
X(a, STATIC,   SINGULAR, UINT32,   control_max_age_us,  30) \
X(a, STATIC,   SINGULAR, UINT32,   frame_ts_fallbacks,  31)
#define AnalogStatus_CALLBACK NULL
#define AnalogStatus_DEFAULT NULL

#define SystemStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    active_set,        1) \
X(a, STATIC,   SINGULAR, UENUM,    signal_state,      2) \
X(a, STATIC,   SINGULAR, UENUM,    ble_read_state,    3) \
X(a, STATIC,   SINGULAR, UENUM,    control_state,     4) \
X(a, STATIC,   SINGULAR, FLOAT,    alpha,             5) \
X(a, STATIC,   SINGULAR, BOOL,     has_alpha,         6) \
X(a, STATIC,   SINGULAR, BOOL,     matrix_a_valid,    7) \
X(a, STATIC,   SINGULAR, BOOL,     matrix_b_valid,    8) \
X(a, STATIC,   SINGULAR, UINT32,   current_cycles,    9) \
X(a, STATIC,   SINGULAR, UINT32,   total_cycles,     10) \
X(a, STATIC,   SINGULAR, UINT32,   monitor_ms,       11) \
X(a, STATIC,   SINGULAR, UINT32,   dead_time_us,     12) \
X(a, STATIC,   SINGULAR, UENUM,    led_mode,         14) \
X(a, STATIC,   SINGULAR, BOOL,     ble_congested,    15) \
X(a, STATIC,   SINGULAR, UINT32,   adc_min,          16) \
X(a, STATIC,   SINGULAR, UINT32,   adc_max,          17) \
X(a, STATIC,   SINGULAR, UINT32,   adc_avg,          18) \
X(a, STATIC,   SINGULAR, UINT32,   dead_time_tail_overhead_cycles,  19) \
X(a, STATIC,   OPTIONAL, MESSAGE,  analog,           20) \
X(a, STATIC,   SINGULAR, UINT32,   signal_edge_overhead_up_cycles,  22) \
X(a, STATIC,   SINGULAR, UINT32,   signal_edge_overhead_down_cycles,  23)
#define SystemStatus_CALLBACK NULL
#define SystemStatus_DEFAULT NULL
#define SystemStatus_analog_MSGTYPE AnalogStatus

#define LogMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    level,             1) \
X(a, STATIC,   SINGULAR, STRING,   text,              2)
#define LogMessage_CALLBACK NULL
#define LogMessage_DEFAULT NULL

#define OtaStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   progress_percent,   2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3) \
X(a, STATIC,   SINGULAR, UINT32,   written_size,      4) \
X(a, STATIC,   SINGULAR, UINT32,   expected_seq,      5)
#define OtaStatus_CALLBACK NULL
#define OtaStatus_DEFAULT NULL

#define OtaBegin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   file_size,         1)
#define OtaBegin_CALLBACK NULL
#define OtaBegin_DEFAULT NULL

#define OtaChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define OtaChunk_CALLBACK NULL
#define OtaChunk_DEFAULT NULL

#define OtaEnd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   sha256,            1)
#define OtaEnd_CALLBACK NULL
#define OtaEnd_DEFAULT NULL

#define OtaCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,begin,type.begin),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,chunk,type.chunk),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,end,type.end),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (type,abort,type.abort),   4)
#define OtaCommand_CALLBACK NULL
#define OtaCommand_DEFAULT NULL
#define OtaCommand_type_begin_MSGTYPE OtaBegin
#define OtaCommand_type_chunk_MSGTYPE OtaChunk
#define OtaCommand_type_end_MSGTYPE OtaEnd

#define UiCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, STRING,   json,              2) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        3)
#define UiCommand_CALLBACK NULL
#define UiCommand_DEFAULT NULL

#define UiCommandResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                3) \
X(a, STATIC,   SINGULAR, STRING,   code,              4) \
X(a, STATIC,   SINGULAR, STRING,   message,           5) \
X(a, STATIC,   SINGULAR, STRING,   json,              6)
#define UiCommandResult_CALLBACK NULL
#define UiCommandResult_DEFAULT NULL

#define AnalogDiagnosticResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     valid,             1) \
X(a, STATIC,   SINGULAR, BOOL,     running,           2) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       3) \
X(a, STATIC,   SINGULAR, UINT64,   elapsed_us,        4) \
X(a, STATIC,   SINGULAR, UINT32,   seq_delta,         5) \
X(a, STATIC,   SINGULAR, UINT32,   miss_delta,        6) \
X(a, STATIC,   SINGULAR, UINT32,   overflow_delta,    7) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               8) \
X(a, STATIC,   SINGULAR, UINT32,   age_us,            9) \
X(a, STATIC,   SINGULAR, UINT32,   rate_tps,         10) \
X(a, STATIC,   SINGULAR, UINT32,   raw_an3,          11) \
X(a, STATIC,   SINGULAR, UINT32,   raw_an5,          12) \
X(a, STATIC,   SINGULAR, UINT32,   raw_an6,          13) \
X(a, STATIC,   SINGULAR, FLOAT,    cal_an3,          14) \
X(a, STATIC,   SINGULAR, FLOAT,    cal_an5,          15) \
X(a, STATIC,   SINGULAR, FLOAT,    cal_an6,          16) \
X(a, STATIC,   SINGULAR, UINT32,   latency_avg_us,   17) \
X(a, STATIC,   SINGULAR, UINT32,   latency_p95_us,   18) \
X(a, STATIC,   SINGULAR, UINT32,   fault_code,       19) \
X(a, STATIC,   SINGULAR, UINT32,   timing_samples,   20) \
X(a, STATIC,   SINGULAR, FLOAT,    playback_avg_us,  21) \
X(a, STATIC,   SINGULAR, FLOAT,    loop_us,          22) \
X(a, STATIC,   SINGULAR, UINT32,   overruns,         23) \
X(a, STATIC,   SINGULAR, UINT32,   timing_faults,    24) \
X(a, STATIC,   SINGULAR, STRING,   message,          25)
#define AnalogDiagnosticResult_CALLBACK NULL
#define AnalogDiagnosticResult_DEFAULT NULL

#define AnalogConfigCaseResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sample_hz,         1) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       2) \
X(a, STATIC,   SINGULAR, UINT64,   elapsed_us,        3) \
X(a, STATIC,   SINGULAR, UINT32,   seq_delta,         4) \
X(a, STATIC,   SINGULAR, UINT32,   rate_tps,          5) \
X(a, STATIC,   SINGULAR, UINT32,   age_us,            6) \
X(a, STATIC,   SINGULAR, UINT32,   miss_delta,        7) \
X(a, STATIC,   SINGULAR, UINT32,   overflow_delta,    8) \
X(a, STATIC,   SINGULAR, UINT32,   fault_code,        9) \
X(a, STATIC,   SINGULAR, UINT32,   latency_avg_us,   10) \
X(a, STATIC,   SINGULAR, UINT32,   latency_p95_us,   11) \
X(a, STATIC,   SINGULAR, UINT32,   playback_avg_us_x100,  12) \
X(a, STATIC,   SINGULAR, UINT32,   loop_us_x100,     13) \
X(a, STATIC,   SINGULAR, UINT32,   overruns_delta,   14) \
X(a, STATIC,   SINGULAR, UINT32,   timing_faults_delta,  15) \
X(a, STATIC,   SINGULAR, UINT32,   dma_samples_delta,  16) \
X(a, STATIC,   SINGULAR, UINT32,   dma_anomalies_delta,  17)
#define AnalogConfigCaseResult_CALLBACK NULL
#define AnalogConfigCaseResult_DEFAULT NULL

#define AnalogConfigTestResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     valid,             1) \
X(a, STATIC,   SINGULAR, BOOL,     running,           2) \
X(a, STATIC,   SINGULAR, UINT32,   case_count,        3) \
X(a, STATIC,   REPEATED, MESSAGE,  cases,             4) \
X(a, STATIC,   SINGULAR, STRING,   message,           5)
#define AnalogConfigTestResult_CALLBACK NULL
#define AnalogConfigTestResult_DEFAULT NULL
#define AnalogConfigTestResult_cases_MSGTYPE AnalogConfigCaseResult

#define BlePacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry,payload.telemetry),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,log,payload.log),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ota_status,payload.ota_status),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,command_result,payload.command_result),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,analog_diagnostic_result,payload.analog_diagnostic_result),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,analog_config_test_result,payload.analog_config_test_result),   7)
#define BlePacket_CALLBACK NULL
#define BlePacket_DEFAULT NULL
#define BlePacket_payload_telemetry_MSGTYPE Telemetry
#define BlePacket_payload_status_MSGTYPE SystemStatus
#define BlePacket_payload_log_MSGTYPE LogMessage
#define BlePacket_payload_ota_status_MSGTYPE OtaStatus
#define BlePacket_payload_command_result_MSGTYPE UiCommandResult
#define BlePacket_payload_analog_diagnostic_result_MSGTYPE AnalogDiagnosticResult
#define BlePacket_payload_analog_config_test_result_MSGTYPE AnalogConfigTestResult

extern const pb_msgdesc_t Telemetry_msg;
extern const pb_msgdesc_t AnalogStatus_msg;
extern const pb_msgdesc_t SystemStatus_msg;
extern const pb_msgdesc_t LogMessage_msg;
extern const pb_msgdesc_t OtaStatus_msg;
extern const pb_msgdesc_t OtaBegin_msg;
extern const pb_msgdesc_t OtaChunk_msg;
extern const pb_msgdesc_t OtaEnd_msg;
extern const pb_msgdesc_t OtaCommand_msg;
extern const pb_msgdesc_t UiCommand_msg;
extern const pb_msgdesc_t UiCommandResult_msg;
extern const pb_msgdesc_t AnalogDiagnosticResult_msg;
extern const pb_msgdesc_t AnalogConfigCaseResult_msg;
extern const pb_msgdesc_t AnalogConfigTestResult_msg;
extern const pb_msgdesc_t BlePacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Telemetry_fields &Telemetry_msg
#define AnalogStatus_fields &AnalogStatus_msg
#define SystemStatus_fields &SystemStatus_msg
#define LogMessage_fields &LogMessage_msg
#define OtaStatus_fields &OtaStatus_msg
#define OtaBegin_fields &OtaBegin_msg
#define OtaChunk_fields &OtaChunk_msg
#define OtaEnd_fields &OtaEnd_msg
#define OtaCommand_fields &OtaCommand_msg
#define UiCommand_fields &UiCommand_msg
#define UiCommandResult_fields &UiCommandResult_msg
#define AnalogDiagnosticResult_fields &AnalogDiagnosticResult_msg
#define AnalogConfigCaseResult_fields &AnalogConfigCaseResult_msg
#define AnalogConfigTestResult_fields &AnalogConfigTestResult_msg
#define BlePacket_fields &BlePacket_msg

/* Maximum encoded size of messages (where known) */
#define AnalogConfigCaseResult_size              109
#define AnalogConfigTestResult_size              551
#define AnalogDiagnosticResult_size              243
#define AnalogStatus_size                        196
#define BlePacket_size                           753
#define LogMessage_size                          132
#define OtaBegin_size                            6
#define OtaChunk_size                            521
#define OtaCommand_size                          524
#define OtaEnd_size                              65
#define OtaStatus_size                           85
#define PROTO_MESSAGING_PB_H_MAX_SIZE            BlePacket_size
#define SystemStatus_size                        289
#define Telemetry_size                           21
#define UiCommandResult_size                     750
#define UiCommand_size                           457

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
