/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_MESSAGING_PB_H_INCLUDED
#define PB_PROTO_MESSAGING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SystemStatus_SignalState {
    SystemStatus_SignalState_STOPPED = 0,
    SystemStatus_SignalState_RUNNING = 1
} SystemStatus_SignalState;

/* Struct definitions */
/* Telemetry message containing analog port readings */
typedef struct _Telemetry {
    float an3;
    float an5;
    float an6;
    uint32_t timestamp_ms;
} Telemetry;

/* System status message (alternative to string-based status) */
typedef struct _SystemStatus {
    SystemStatus_SignalState state;
    float alpha;
    uint32_t cycle_count;
} SystemStatus;

/* Top-level message for BLE communication */
typedef struct _BlePacket {
    pb_size_t which_payload;
    union {
        Telemetry telemetry;
        SystemStatus status;
    } payload;
} BlePacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SystemStatus_SignalState_MIN SystemStatus_SignalState_STOPPED
#define _SystemStatus_SignalState_MAX SystemStatus_SignalState_RUNNING
#define _SystemStatus_SignalState_ARRAYSIZE ((SystemStatus_SignalState)(SystemStatus_SignalState_RUNNING+1))


#define SystemStatus_state_ENUMTYPE SystemStatus_SignalState



/* Initializer values for message structs */
#define Telemetry_init_default                   {0, 0, 0, 0}
#define SystemStatus_init_default                {_SystemStatus_SignalState_MIN, 0, 0}
#define BlePacket_init_default                   {0, {Telemetry_init_default}}
#define Telemetry_init_zero                      {0, 0, 0, 0}
#define SystemStatus_init_zero                   {_SystemStatus_SignalState_MIN, 0, 0}
#define BlePacket_init_zero                      {0, {Telemetry_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Telemetry_an3_tag                        1
#define Telemetry_an5_tag                        2
#define Telemetry_an6_tag                        3
#define Telemetry_timestamp_ms_tag               4
#define SystemStatus_state_tag                   1
#define SystemStatus_alpha_tag                   2
#define SystemStatus_cycle_count_tag             3
#define BlePacket_telemetry_tag                  1
#define BlePacket_status_tag                     2

/* Struct field encoding specification for nanopb */
#define Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    an3,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    an5,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    an6,               3) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      4)
#define Telemetry_CALLBACK NULL
#define Telemetry_DEFAULT NULL

#define SystemStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    alpha,             2) \
X(a, STATIC,   SINGULAR, UINT32,   cycle_count,       3)
#define SystemStatus_CALLBACK NULL
#define SystemStatus_DEFAULT NULL

#define BlePacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry,payload.telemetry),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   2)
#define BlePacket_CALLBACK NULL
#define BlePacket_DEFAULT NULL
#define BlePacket_payload_telemetry_MSGTYPE Telemetry
#define BlePacket_payload_status_MSGTYPE SystemStatus

extern const pb_msgdesc_t Telemetry_msg;
extern const pb_msgdesc_t SystemStatus_msg;
extern const pb_msgdesc_t BlePacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Telemetry_fields &Telemetry_msg
#define SystemStatus_fields &SystemStatus_msg
#define BlePacket_fields &BlePacket_msg

/* Maximum encoded size of messages (where known) */
#define BlePacket_size                           23
#define PROTO_MESSAGING_PB_H_MAX_SIZE            BlePacket_size
#define SystemStatus_size                        13
#define Telemetry_size                           21

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
