r:
	npm run start

t: tailwind

up: 
	cp -rf img ../../docs
	cp -rf videos ../../docs
	cp -rf plugin ../../docs
	cp -rf index.html ../../docs

down: 
	cp -rf ../../docs/videos .
	cp -rf ../../docs/img .
	cp -rf ../../docs/index.html .

tw: tailwind
	
tailwind:
	npm run tw