function metrics = collect_metrics(benchmark, model, controller, summary, region)
%COLLECT_METRICS Assemble the stable, publication-facing metric names and units.
A_normalized = benchmark.state_scale \ model.Phi * benchmark.state_scale;
B_normalized = benchmark.state_scale \ model.Gamma * benchmark.timing_scale;
metrics = struct( ...
    'nominal_period_us', benchmark.period * 1e6, ...
    'nominal_interval_count', numel(benchmark.dynamics_indices), ...
    'nominal_closure_error_inf', model.nominal_closure_error, ...
    'nominal_minimum_dwell_us', min(benchmark.nominal_dwell) * 1e6, ...
    'benchmark_design_dwell_bound_us', benchmark.benchmark_design_dwell_bound * 1e6, ...
    'applied_schedule_dwell_bound_us', benchmark.applied_schedule_dwell_bound * 1e6, ...
    'max_published_boundary_correction_us', ...
        benchmark.max_published_boundary_correction * 1e6, ...
    'cycle_average_vc1_v', model.cycle_average_state(1), ...
    'cycle_average_vc2_v', model.cycle_average_state(2), ...
    'cycle_average_il_a', model.cycle_average_state(3), ...
    'timing_scale_us', benchmark.timing_scale * 1e6, ...
    'phi_fd_relative_error', model.phi_relative_error, ...
    'gamma_fd_relative_error', model.gamma_relative_error, ...
    'phi_fd_max_absolute_error', model.phi_max_absolute_error, ...
    'gamma_fd_max_absolute_error', model.gamma_max_absolute_error, ...
    'residual_slope', model.residual_slope, ...
    'open_loop_spectral_radius', max(abs(eig(benchmark.state_scale \ model.Phi * benchmark.state_scale))), ...
    'conservative_spectral_radius', max(abs(eig(A_normalized - B_normalized * controller.K_conservative_normalized))), ...
    'aggressive_spectral_radius', max(abs(eig(A_normalized - B_normalized * controller.K_aggressive_normalized))), ...
    'invariant_region_facets', region.metrics.facet_count, ...
    'invariant_region_vertices', region.metrics.vertex_count, ...
    'invariant_region_volume_physical', region.metrics.volume_physical, ...
    'invariant_region_vc1_min_v', region.metrics.ranges_physical(1, 1), ...
    'invariant_region_vc1_max_v', region.metrics.ranges_physical(2, 1), ...
    'invariant_region_vc2_min_v', region.metrics.ranges_physical(1, 2), ...
    'invariant_region_vc2_max_v', region.metrics.ranges_physical(2, 2), ...
    'invariant_region_il_min_a', region.metrics.ranges_physical(1, 3), ...
    'invariant_region_il_max_a', region.metrics.ranges_physical(2, 3), ...
    'invariant_region_iterations', region.iterations, ...
    'invariant_region_origin_margin', region.metrics.origin_strict_margin, ...
    'invariant_region_vertex_dwell_margin_us', ...
        region.metrics.minimum_vertex_dwell_margin * 1e6, ...
    'invariant_region_image_dwell_margin_us', ...
        region.metrics.minimum_image_dwell_margin * 1e6, ...
    'invariant_region_max_violation', max(0, region.metrics.invariance_violation), ...
    'raw_and_invariant_regions_coincide', region.regions_coincide, ...
    'initial_state_in_invariant_region', region.metrics.initial_state_in_invariant_region, ...
    'first_invariant_region_cycle', region.metrics.first_invariant_region_cycle, ...
    'lower_comparison_beta', region.comparison_betas(1), ...
    'middle_comparison_beta', region.comparison_betas(2), ...
    'lower_comparison_region_volume_physical', ...
        region.metrics.comparison_volumes_physical(1), ...
    'middle_comparison_region_volume_physical', ...
        region.metrics.comparison_volumes_physical(2), ...
    'lower_comparison_region_volume_ratio', ...
        region.metrics.comparison_volume_ratios(1), ...
    'middle_comparison_region_volume_ratio', ...
        region.metrics.comparison_volume_ratios(2), ...
    'aggressive_input_weight', benchmark.aggressive_input_weight, ...
    'conservative_input_weight', benchmark.conservative_input_weight, ...
    'initial_normalized_error', summary.initial_error, ...
    'conditioned_final_error', summary.conditioned_final_error, ...
    'conservative_final_error', summary.conservative_final_error, ...
    'open_loop_final_error', summary.open_loop_final_error, ...
    'conditioned_first_cycle_below_001', summary.conditioned_first_cycle_below_001, ...
    'conservative_first_cycle_below_001', summary.conservative_first_cycle_below_001, ...
    'long_simulation_cycles', benchmark.long_simulation_cycles, ...
    'long_open_loop_convergence_cycle', summary.long_open_loop_convergence_cycle, ...
    'conditioned_cycles', summary.conditioned_cycle_count, ...
    'minimum_conditioning_beta', summary.minimum_conditioning_beta, ...
    'maximum_raw_offset_us', summary.maximum_raw_offset * 1e6, ...
    'maximum_applied_offset_us', summary.maximum_applied_offset * 1e6, ...
    'minimum_raw_dwell_us', summary.minimum_raw_dwell * 1e6, ...
    'minimum_applied_dwell_us', summary.minimum_applied_dwell * 1e6, ...
    'minimum_conservative_dwell_us', summary.minimum_conservative_dwell * 1e6, ...
    'simulation_cycles', benchmark.cycle_count);
end
