function controller = design_feedback(benchmark, model)
%DESIGN_FEEDBACK Aggressive and conservative LQR, with explicit unit conversion.
A_normalized = benchmark.state_scale \ model.Phi * benchmark.state_scale;
B_normalized = benchmark.state_scale \ model.Gamma * benchmark.timing_scale;
Q_normalized = eye(size(model.Phi, 1));
K_aggressive_normalized = dlqr(A_normalized, B_normalized, ...
    Q_normalized, benchmark.aggressive_input_weight * eye(size(model.Gamma, 2)));
K_conservative_normalized = dlqr(A_normalized, B_normalized, ...
    Q_normalized, benchmark.conservative_input_weight * eye(size(model.Gamma, 2)));
K_aggressive_physical = benchmark.timing_scale * K_aggressive_normalized / benchmark.state_scale;
K_conservative_physical = benchmark.timing_scale * K_conservative_normalized / benchmark.state_scale;
A_aggressive = A_normalized - B_normalized * K_aggressive_normalized;
A_conservative = A_normalized - B_normalized * K_conservative_normalized;
conservative_spectral_radius = max(abs(eig(A_conservative)));
aggressive_spectral_radius = max(abs(eig(A_aggressive)));
assert(aggressive_spectral_radius < 1 && conservative_spectral_radius < 1, ...
    'A normalized LQR closed loop is not Schur stable.');
controller = struct('state_scale', benchmark.state_scale, 'timing_scale', benchmark.timing_scale, ...
    'Q_normalized', Q_normalized, ...
    'aggressive_input_weight', benchmark.aggressive_input_weight, ...
    'conservative_input_weight', benchmark.conservative_input_weight, ...
    'K_aggressive_normalized', K_aggressive_normalized, ...
    'K_conservative_normalized', K_conservative_normalized, ...
    'K_aggressive_physical', K_aggressive_physical, ...
    'K_conservative_physical', K_conservative_physical);
end
