function certificate = export_lyapunov(paths, benchmark, model, controller)
%EXPORT_LYAPUNOV Adopt and recheck the Julia certificate against the article model.
% No rounded tutorial values and no embedded stale endpoint matrices are used.
study = fullfile(paths.root, 'studies', 'lyapunov', 'results');
python = jsondecode(fileread(fullfile(study, 'certificate.json')));
julia = jsondecode(fileread(fullfile(study, 'lyapunov_analysis_julia_certificate.json')));
assert(strcmp(julia.solver.status, 'OPTIMAL'), 'Julia solve was not optimal.');
S = benchmark.state_scale;
A0 = S \ model.Phi * S;
B = S \ model.Gamma * benchmark.timing_scale;
A1 = A0 - B * controller.K_aggressive_normalized;
endpoint_error = [norm(A0 - python.A0, 'fro'), norm(A1 - python.A1, 'fro')];
assert(max(endpoint_error) < 1e-9, ...
    'Study endpoints differ from the article model/gain; reconstruct and solve the study.');
certificate = paper.verify_common_lyapunov(A0, A1, julia.P);
assert(abs(certificate.q - julia.q) < 1e-10, 'Julia decrease margin disagrees.');
assert(julia.eta > 0 && certificate.q >= julia.eta - 1e-10, ...
    'The returned P does not attain the reported decrease margin.');
certificate.eta = julia.eta;
certificate.solver = julia.solver;
certificate.endpoint_model_error = endpoint_error;
certificate.source = 'studies/lyapunov/analysis.jl and its full-precision JSON output';
certificate.scope = 'Conditioned linearized family; floating-point verification';
% Check that the displayed matrix retains strict decrease, but use full precision
% for every reported bound and for the machine-readable publication certificate.
paper.verify_common_lyapunov(A0, A1, round(certificate.P, 6));
write_text(fullfile(paths.results, 'lyapunov_certificate.json'), ...
    jsonencode(certificate, 'PrettyPrint', true));
file = fopen(fullfile(paths.output, 'latex', 'lyapunov_metrics.tex'), 'w');
assert(file ~= -1, 'Could not open Lyapunov metric export.');
cleanup = onCleanup(@() fclose(file));
fprintf(file, '%% Generated by paper.export_lyapunov from the Julia certificate.\n');
write_macro(file, 'LyapunovEta', certificate.eta, '%.9e');
write_macro(file, 'LyapunovMinEigenvalue', min(certificate.eigP), '%.9e');
write_macro(file, 'LyapunovEndpointZeroDecrease', min(certificate.eigQ0), '%.9e');
write_macro(file, 'LyapunovEndpointOneDecrease', min(certificate.eigQ1), '%.9e');
write_macro(file, 'LyapunovDecrease', certificate.q, '%.9e');
write_macro(file, 'LyapunovRateBound', certificate.rho_bound, '%.12f');
fprintf(file, '\\newcommand{\\LyapunovMatrix}{\\begin{bmatrix}\n');
for row = 1:size(certificate.P, 1)
    fprintf(file, '%.6f & %.6f & %.6f', certificate.P(row, :));
    if row < size(certificate.P, 1), fprintf(file, '\\\\\n'); end
end
fprintf(file, '\n\\end{bmatrix}}\n');
fprintf('Common-P certificate: min eig(P) %.9g, decrease %.9g, rate bound %.12f\n', ...
    min(certificate.eigP), certificate.q, certificate.rho_bound);
end

function write_macro(file, name, value, format)
fprintf(file, '\\newcommand{\\%s}{%s}\n', name, sprintf(format, value));
end

function write_text(filename, text)
file = fopen(filename, 'w');
assert(file ~= -1, 'Could not open %s', filename);
cleanup = onCleanup(@() fclose(file));
fprintf(file, '%s\n', text);
end
