function paths = paths(output_root)
%PATHS Resolve inputs from this file, never from the current working directory.
% An alternate output root allows regression runs without overwriting evidence.
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
if nargin == 0 || isempty(output_root)
    output_root = root;
end
paths = struct( ...
    'root', root, ...
    'output', output_root, ...
    'simulation', fullfile(root, '..', '..', '..', 'simulations', 'matlab-sim'), ...
    'results', fullfile(output_root, 'results'), ...
    'metrics_tex', fullfile(output_root, 'latex', 'metrics.tex'), ...
    'article_figures', fullfile(output_root, 'latex', 'figures'), ...
    'diagnostic_figures', fullfile(output_root, 'results', 'figures'));
end
