function print_summary(paths, benchmark, model, summary, region, metrics)
%PRINT_SUMMARY Report validation and simulation results without recomputing them.
fprintf('Generated focused paper results in %s\n', paths.output);
fprintf('Three-cell converter schedule: %d intervals, T = %.3f us\n', ...
    numel(benchmark.dynamics_indices), benchmark.period * 1e6);
fprintf('Nominal closure error (inf norm): %.3e\n', model.nominal_closure_error);
fprintf('Cycle-average state: [%.6f, %.6f, %.6f]\n', model.cycle_average_state);
fprintf('Relative Jacobian errors (Phi, Gamma): %.3e, %.3e\n', ...
    model.phi_relative_error, model.gamma_relative_error);
fprintf('Perturbation residual slope: %.6f\n', model.residual_slope);
fprintf('Spectral radii (open, conservative, aggressive): %.9f, %.9f, %.9f\n', ...
    metrics.open_loop_spectral_radius, metrics.conservative_spectral_radius, ...
    metrics.aggressive_spectral_radius);
fprintf(['Invariant raw-action region: %d facets, %d vertices, ', ...
    'volume %.9g V^2 A\n'], region.metrics.facet_count, ...
    region.metrics.vertex_count, region.metrics.volume_physical);
fprintf(['Invariant-region ranges (e_vc1, e_vc2, e_il): ', ...
    '[%.6f, %.6f], [%.6f, %.6f], [%.6f, %.6f]\n'], ...
    region.metrics.ranges_physical(:, 1), ...
    region.metrics.ranges_physical(:, 2), ...
    region.metrics.ranges_physical(:, 3));
fprintf(['Invariant iteration count: %d; raw and invariant regions ', ...
    'coincide: %d; first conditioned-trajectory entry: cycle %d\n'], ...
    region.iterations, region.regions_coincide, region.metrics.first_invariant_region_cycle);
fprintf(['Minimum vertex/image dwell margins: %.9g / %.9g us; ', ...
    'maximum invariance violation: %.3e\n'], ...
    region.metrics.minimum_vertex_dwell_margin * 1e6, ...
    region.metrics.minimum_image_dwell_margin * 1e6, max(0, region.metrics.invariance_violation));
for index = 1:numel(region.comparison_betas)
    fprintf(['Fixed-beta comparison: beta %.3f, volume %.9g V^2 A, ', ...
        'volume ratio %.6f, invariant %d\n'], region.comparison_betas(index), ...
        region.metrics.comparison_volumes_physical(index), ...
        region.metrics.comparison_volume_ratios(index), ...
        region.comparison_regions_are_invariant(index));
end
fprintf('Conditioned cycles: %d; minimum beta: %.9f\n', ...
    summary.conditioned_cycle_count, summary.minimum_conditioning_beta);
fprintf('Maximum raw/applied offset: %.6f / %.6f us\n', ...
    summary.maximum_raw_offset * 1e6, summary.maximum_applied_offset * 1e6);
fprintf('Minimum raw/applied dwell: %.6f / %.6f us (bound %.3f us)\n', ...
    summary.minimum_raw_dwell * 1e6, summary.minimum_applied_dwell * 1e6, ...
    benchmark.applied_schedule_dwell_bound * 1e6);
fprintf('Minimum unconditioned conservative dwell: %.6f us\n', ...
    summary.minimum_conservative_dwell * 1e6);
fprintf('First cycle below 0.01 (conditioned, conservative): %d, %d\n', ...
    summary.conditioned_first_cycle_below_001, summary.conservative_first_cycle_below_001);
fprintf(['Exact final normalized errors (conditioned, conservative, open): ', ...
    '%.9e, %.9e, %.9e\n'], summary.conditioned_final_error, ...
    summary.conservative_final_error, summary.open_loop_final_error);
fprintf(['Long-horizon open-loop convergence: cycle %d; final errors ', ...
    '(conditioned, open) = %.9e, %.9e\n'], ...
    summary.long_open_loop_convergence_cycle, summary.long_conditioned_final_error, ...
    summary.long_open_loop_final_error);
fprintf('Maximum published-boundary correction: %.6f us\n', ...
    benchmark.max_published_boundary_correction * 1e6);
end
