function fig = publication_figure(height_cm)
%PUBLICATION_FIGURE Match the manuscript's 160 mm full text width.
% Export at this physical size and include at \textwidth, without shrinking.
fig = figure('Visible', 'off', 'Color', 'w', 'Units', 'centimeters', ...
    'Position', [2, 2, 16, height_cm], ...
    'DefaultAxesFontName', 'Times New Roman', 'DefaultAxesFontSize', 9, ...
    'DefaultAxesLabelFontSizeMultiplier', 10/9, ...
    'DefaultAxesTitleFontSizeMultiplier', 10/9, ...
    'DefaultAxesTitleFontWeight', 'normal', ...
    'DefaultTextFontName', 'Times New Roman', 'DefaultTextFontSize', 9, ...
    'DefaultLegendFontName', 'Times New Roman', 'DefaultLegendFontSize', 9, ...
    'DefaultLineLineWidth', 1.1);
end
