function [response, summary, long_response] = simulate_responses(benchmark, controller)
%SIMULATE_RESPONSES Exact nonlinear conditioned, conservative, and open-loop runs.
% The 100-cycle comparison and 100000-cycle convergence check are separate below.

%% Compare the three policies over the article's 100-cycle horizon
[conditioned_states, raw_offsets, applied_offsets, raw_dwell, ...
    applied_dwell, conditioning_beta, conditioned_boundary_states] = ...
    simulate_conditioned_cycles(benchmark.config, benchmark.orbit_anchor, benchmark.initial_state, ...
    controller.K_aggressive_physical, benchmark.cycle_count, benchmark.applied_schedule_dwell_bound);
[conservative_states, conservative_offsets, conservative_dwell] = ...
    simulate_raw_cycles(benchmark.config, benchmark.orbit_anchor, benchmark.initial_state, ...
    controller.K_conservative_physical, benchmark.cycle_count);
[open_loop_states, ~, open_loop_dwell, open_boundary_states] = ...
    simulate_raw_cycles(benchmark.config, benchmark.orbit_anchor, benchmark.initial_state, ...
    zeros(size(controller.K_aggressive_physical)), benchmark.cycle_count);

conditioned_error = vecnorm(benchmark.state_scale \ ...
    (conditioned_states - benchmark.orbit_anchor), 2, 1)';
conservative_error = vecnorm(benchmark.state_scale \ ...
    (conservative_states - benchmark.orbit_anchor), 2, 1)';
open_loop_error = vecnorm(benchmark.state_scale \ ...
    (open_loop_states - benchmark.orbit_anchor), 2, 1)';
initial_error = conditioned_error(1);
conditioned_final_error = conditioned_error(end);
conservative_final_error = conservative_error(end);
open_loop_final_error = open_loop_error(end);
conditioned_first_cycle_below_001 = find(conditioned_error < 0.01, 1) - 1;
conservative_first_cycle_below_001 = find(conservative_error < 0.01, 1) - 1;
assert(~isempty(conditioned_first_cycle_below_001) && ...
    ~isempty(conservative_first_cycle_below_001), ...
    'A controller does not settle below normalized error 0.01 in 100 cycles.');

%% Long-horizon check of eventual open-loop convergence
[long_conditioned_states, long_open_loop_states] = ...
    simulate_cycle_start_trajectories(benchmark.config, benchmark.orbit_anchor, benchmark.initial_state, ...
    controller.K_aggressive_physical, benchmark.long_simulation_cycles, ...
    benchmark.applied_schedule_dwell_bound);
long_conditioned_error = vecnorm(benchmark.state_scale \ ...
    (long_conditioned_states - benchmark.orbit_anchor), 2, 1)';
long_open_loop_error = vecnorm(benchmark.state_scale \ ...
    (long_open_loop_states - benchmark.orbit_anchor), 2, 1)';
last_open_loop_outside = find(long_open_loop_error >= 0.01, 1, 'last');
if isempty(last_open_loop_outside)
    long_open_loop_convergence_cycle = 0;
else
    long_open_loop_convergence_cycle = last_open_loop_outside;
end
assert(long_open_loop_convergence_cycle <= benchmark.long_simulation_cycles, ...
    'The long-horizon trajectory comparison did not remain below the error threshold.');
long_response = struct('open_loop_states', long_open_loop_states, ...
    'open_loop_error', long_open_loop_error, ...
    'convergence_cycle', long_open_loop_convergence_cycle);

%% Check the dwell constraints and summarize the transient
conditioned_cycle_count = sum(conditioning_beta < 1 - 1e-12);
minimum_conditioning_beta = min(conditioning_beta);
maximum_raw_offset = max(abs(raw_offsets), [], 'all');
maximum_applied_offset = max(abs(applied_offsets), [], 'all');
minimum_raw_dwell = min(raw_dwell, [], 'all');
minimum_applied_dwell = min(applied_dwell, [], 'all');
minimum_conservative_dwell = min(conservative_dwell, [], 'all');
assert(all(applied_dwell >= benchmark.applied_schedule_dwell_bound - 1e-12, 'all'), ...
    'A conditioned schedule violates the applied dwell bound.');
assert(conditioned_cycle_count > 0 && minimum_conditioning_beta < 1, ...
    'The aggressive controller does not exercise dwell-time conditioning.');
assert(conditioned_first_cycle_below_001 < conservative_first_cycle_below_001, ...
    'The conditioned aggressive controller is not faster than the conservative one.');
assert(any(raw_dwell < benchmark.applied_schedule_dwell_bound, 'all') && ...
    minimum_raw_dwell < 0, ...
    'The raw aggressive schedule is never infeasible or inverted.');
assert(conditioned_final_error < conservative_final_error && ...
    conditioned_final_error < open_loop_final_error, ...
    'The conditioned aggressive response does not have the smallest final error.');
assert(all(open_loop_dwell > benchmark.applied_schedule_dwell_bound, 'all'), ...
    'The open-loop schedule violates the strict 3 us applied-schedule bound.');

%% Preserve the response schema consumed by the article and independent studies
response = struct('initial_state', benchmark.initial_state, ...
    'conditioned_states', conditioned_states, ...
    'conservative_states', conservative_states, ...
    'open_loop_states', open_loop_states, ...
    'conditioned_error', conditioned_error, ...
    'conservative_error', conservative_error, ...
    'open_loop_error', open_loop_error, ...
    'raw_offsets', raw_offsets, 'applied_offsets', applied_offsets, ...
    'conservative_offsets', conservative_offsets, ...
    'raw_dwell', raw_dwell, 'applied_dwell', applied_dwell, ...
    'conservative_dwell', conservative_dwell, ...
    'conditioning_beta', conditioning_beta, ...
    'conditioned_boundary_states', conditioned_boundary_states, ...
    'open_boundary_states', open_boundary_states);

summary = struct( ...
    'initial_error', initial_error, ...
    'conditioned_final_error', conditioned_final_error, ...
    'conservative_final_error', conservative_final_error, ...
    'open_loop_final_error', open_loop_final_error, ...
    'conditioned_first_cycle_below_001', conditioned_first_cycle_below_001, ...
    'conservative_first_cycle_below_001', conservative_first_cycle_below_001, ...
    'long_open_loop_convergence_cycle', long_open_loop_convergence_cycle, ...
    'conditioned_cycle_count', conditioned_cycle_count, ...
    'minimum_conditioning_beta', minimum_conditioning_beta, ...
    'maximum_raw_offset', maximum_raw_offset, ...
    'maximum_applied_offset', maximum_applied_offset, ...
    'minimum_raw_dwell', minimum_raw_dwell, ...
    'minimum_applied_dwell', minimum_applied_dwell, ...
    'minimum_conservative_dwell', minimum_conservative_dwell);
summary.long_conditioned_final_error = long_conditioned_error(end);
summary.long_open_loop_final_error = long_open_loop_error(end);
end

function [states, raw_offsets, applied_offsets, raw_dwell, ...
        applied_dwell, beta, boundary_states] = simulate_conditioned_cycles( ...
        config, orbit_anchor, initial_state, gain, cycle_count, dwell_bound)
    state_count = numel(initial_state);
    interval_count = numel(config.Omega);
    timing_count = interval_count - 1;
    states = zeros(state_count, cycle_count + 1);
    raw_offsets = zeros(timing_count, cycle_count);
    applied_offsets = zeros(timing_count, cycle_count);
    raw_dwell = zeros(interval_count, cycle_count);
    applied_dwell = zeros(interval_count, cycle_count);
    beta = ones(cycle_count, 1);
    boundary_states = zeros(state_count, cycle_count * interval_count + 1);
    states(:, 1) = initial_state;
    boundary_states(:, 1) = initial_state;

    for cycle = 1:cycle_count
        raw_offsets(:, cycle) = -gain * (states(:, cycle) - orbit_anchor);
        raw_boundaries = config.Ts(:) + [0; raw_offsets(:, cycle); 0];
        raw_dwell(:, cycle) = diff(raw_boundaries);
        [applied_offsets(:, cycle), beta(cycle), applied_dwell(:, cycle)] = ...
            condition_dwell_times(config.Ts, raw_offsets(:, cycle), dwell_bound);
        cycle_states = paper.cycle_boundaries( ...
            config, states(:, cycle), applied_offsets(:, cycle));
        states(:, cycle + 1) = cycle_states(:, end);
        first = (cycle - 1) * interval_count + 2;
        boundary_states(:, first:(first + interval_count - 1)) = ...
            cycle_states(:, 2:end);
    end
end

function [states, offsets, dwell, boundary_states] = simulate_raw_cycles( ...
        config, orbit_anchor, initial_state, gain, cycle_count)
    state_count = numel(initial_state);
    interval_count = numel(config.Omega);
    timing_count = interval_count - 1;
    states = zeros(state_count, cycle_count + 1);
    offsets = zeros(timing_count, cycle_count);
    dwell = zeros(interval_count, cycle_count);
    boundary_states = zeros(state_count, cycle_count * interval_count + 1);
    states(:, 1) = initial_state;
    boundary_states(:, 1) = initial_state;

    for cycle = 1:cycle_count
        offsets(:, cycle) = -gain * (states(:, cycle) - orbit_anchor);
        boundaries = config.Ts(:) + [0; offsets(:, cycle); 0];
        dwell(:, cycle) = diff(boundaries);
        assert(all(dwell(:, cycle) > 0), ...
            'Raw cycle propagation received a nonpositive dwell.');
        cycle_states = paper.cycle_boundaries( ...
            config, states(:, cycle), offsets(:, cycle));
        states(:, cycle + 1) = cycle_states(:, end);
        first = (cycle - 1) * interval_count + 2;
        boundary_states(:, first:(first + interval_count - 1)) = ...
            cycle_states(:, 2:end);
    end
end

function [conditioned_states, open_states] = ...
        simulate_cycle_start_trajectories(config, orbit_anchor, initial_state, ...
        gain, cycle_count, dwell_bound)
    state_count = numel(initial_state);
    interval_count = numel(config.Omega);
    conditioned_states = zeros(state_count, cycle_count + 1);
    open_states = zeros(state_count, cycle_count + 1);
    conditioned_states(:, 1) = initial_state;
    open_states(:, 1) = initial_state;

    for cycle = 1:cycle_count
        raw_offsets = -gain * (conditioned_states(:, cycle) - orbit_anchor);
        [applied_offsets, ~, ~] = condition_dwell_times( ...
            config.Ts, raw_offsets, dwell_bound);
        conditioned_states(:, cycle + 1) = paper.exact_cycle( ...
            config, conditioned_states(:, cycle), applied_offsets);
        open_states(:, cycle + 1) = paper.exact_cycle( ...
            config, open_states(:, cycle), zeros(interval_count - 1, 1));
    end
end


