function model = validate_model(benchmark)
%VALIDATE_MODEL Linearize, check cycle closure and Jacobians, and fit residual decay.
% No controller design, simulation exports, or figure generation occurs here.
linearization = Dynamics.linearize_cycle(benchmark.config);
Phi = linearization.Phi;
Gamma = linearization.Gamma;
nominal_cycle_end = paper.exact_cycle(benchmark.config, benchmark.orbit_anchor, zeros(size(Gamma, 2), 1));
nominal_closure_error = norm(nominal_cycle_end - benchmark.orbit_anchor, inf);
cycle_average_state = exact_cycle_average(benchmark.config, benchmark.orbit_anchor);
assert(nominal_closure_error < 1e-10, ...
    'The nominal augmented-exponential cycle does not close.');

%% Central finite-difference verification of both Jacobians
[Phi_fd, Gamma_fd, state_fd_step, timing_fd_step] = ...
    central_jacobians(benchmark.config, benchmark.orbit_anchor, benchmark.state_scale, benchmark.timing_scale);
phi_relative_error = norm(Phi_fd - Phi, 'fro') / norm(Phi, 'fro');
gamma_relative_error = norm(Gamma_fd - Gamma, 'fro') / norm(Gamma, 'fro');
phi_max_absolute_error = max(abs(Phi_fd - Phi), [], 'all');
gamma_max_absolute_error = max(abs(Gamma_fd - Gamma), [], 'all');
assert(phi_relative_error < 1e-7, ...
    'The state Jacobian disagrees with its central finite difference.');
assert(gamma_relative_error < 1e-7, ...
    'The switching-instant Jacobian disagrees with its central finite difference.');

%% Combined normalized perturbation scaling
perturbation_sizes = logspace(-3, -1, 9)';
direction = [0.60; -0.70; 0.40; 0.80; -0.60; 0.50; -0.40; ...
    0.30; -0.20; 0.70; -0.50];
assert(numel(direction) == size(Phi, 1) + size(Gamma, 2), ...
    'The combined perturbation must cover all state and timing inputs.');
direction = direction / norm(direction);
normalized_residual = zeros(size(perturbation_sizes));
for index = 1:numel(perturbation_sizes)
    amplitude = perturbation_sizes(index);
    state_perturbation = benchmark.state_scale * ...
        (amplitude * direction(1:3));
    timing_perturbation = benchmark.timing_scale * ...
        (amplitude * direction(4:end));
    exact_end = paper.exact_cycle(benchmark.config, ...
        benchmark.orbit_anchor + state_perturbation, timing_perturbation);
    linear_end = benchmark.orbit_anchor + Phi * state_perturbation ...
        + Gamma * timing_perturbation;
    normalized_residual(index) = ...
        norm(benchmark.state_scale \ (exact_end - linear_end), 2);
end
fit_coefficients = polyfit(log10(perturbation_sizes), ...
    log10(normalized_residual), 1);
residual_slope = fit_coefficients(1);
fitted_residual = 10 .^ polyval(fit_coefficients, ...
    log10(perturbation_sizes));
assert(residual_slope > 1.85 && residual_slope < 2.15, ...
    'The local linearization residual does not scale quadratically.');


model = struct( ...
    'linearization', linearization, ...
    'Phi', Phi, ...
    'Gamma', Gamma, ...
    'nominal_closure_error', nominal_closure_error, ...
    'cycle_average_state', cycle_average_state, ...
    'Phi_fd', Phi_fd, ...
    'Gamma_fd', Gamma_fd, ...
    'state_fd_step', state_fd_step, ...
    'timing_fd_step', timing_fd_step, ...
    'phi_relative_error', phi_relative_error, ...
    'gamma_relative_error', gamma_relative_error, ...
    'phi_max_absolute_error', phi_max_absolute_error, ...
    'gamma_max_absolute_error', gamma_max_absolute_error, ...
    'perturbation_sizes', perturbation_sizes, ...
    'normalized_residual', normalized_residual, ...
    'fitted_residual', fitted_residual, ...
    'residual_slope', residual_slope);
end

function average_state = exact_cycle_average(config, state_start)
    state_count = numel(state_start);
    state = state_start(:);
    integral = zeros(state_count, 1);
    boundary_times = config.Ts(:);
    for interval = 1:numel(config.Omega)
        mode = config.Omega(interval);
        generator = [config.A{mode}, config.b{mode}, ...
                zeros(state_count, state_count); ...
            zeros(1, 2 * state_count + 1); ...
            eye(state_count), zeros(state_count, state_count + 1)];
        duration = boundary_times(interval + 1) - boundary_times(interval);
        augmented_state = expm(generator * duration) * ...
            [state; 1; zeros(state_count, 1)];
        state = augmented_state(1:state_count);
        integral = integral + augmented_state(state_count + 2:end);
    end
    average_state = integral / ...
        (boundary_times(end) - boundary_times(1));
end

function [Phi_fd, Gamma_fd, state_step, timing_step] = ...
        central_jacobians(config, orbit_anchor, state_scale, timing_scale)
    state_count = numel(orbit_anchor);
    timing_count = numel(config.Omega) - 1;
    Phi_fd = zeros(state_count);
    Gamma_fd = zeros(state_count, timing_count);
    state_step = 1e-4 * diag(state_scale);
    timing_step = 1e-3 * timing_scale;
    zero_offsets = zeros(timing_count, 1);

    for column = 1:state_count
        perturbation = zeros(state_count, 1);
        perturbation(column) = state_step(column);
        plus = paper.exact_cycle(config, orbit_anchor + perturbation, zero_offsets);
        minus = paper.exact_cycle(config, orbit_anchor - perturbation, zero_offsets);
        Phi_fd(:, column) = (plus - minus) / (2 * state_step(column));
    end
    for column = 1:timing_count
        perturbation = zeros(timing_count, 1);
        perturbation(column) = timing_step;
        plus = paper.exact_cycle(config, orbit_anchor, perturbation);
        minus = paper.exact_cycle(config, orbit_anchor, -perturbation);
        Gamma_fd(:, column) = (plus - minus) / (2 * timing_step);
    end
end

