function write_provenance(paths)
%WRITE_PROVENANCE Record the environment separately from publication metrics.
[revision_status, revision] = system(sprintf('git -C "%s" rev-parse HEAD', paths.root));
[status_status, working_tree] = system(sprintf('git -C "%s" status --porcelain', paths.root));
if revision_status ~= 0, revision = 'unavailable'; end
if status_status ~= 0, working_tree = 'unavailable'; end
record = struct( ...
    'command', 'task results', ...
    'source_revision', strtrim(revision), ...
    'working_tree_status', strtrim(working_tree), ...
    'generated_at', char(datetime('now', 'TimeZone', 'UTC', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ssXXX')), ...
    'matlab_version', version, ...
    'toolboxes', ver, ...
    'mpt_class', which('Polyhedron'));
file = fopen(fullfile(paths.results, 'provenance.json'), 'w');
assert(file ~= -1, 'Could not write numerical provenance.');
cleanup = onCleanup(@() fclose(file));
fprintf(file, '%s\n', jsonencode(record, PrettyPrint=true));
end
