function results = write_outputs(paths, benchmark, model, controller, region, response, metrics)
%WRITE_OUTPUTS Serialize CSV, LaTeX macros, and the existing paper_results.mat schema.
    writetable(struct2table(metrics), fullfile(paths.results, 'metrics.csv'));
    write_metrics_tex(paths.metrics_tex, metrics);

    interval = (1:numel(benchmark.config.Omega))';
    dynamics_index = benchmark.config.Omega(:);
    published_mode = dynamics_index - 1;
    start_us = benchmark.config.Ts(1:end-1)' * 1e6;
    end_us = benchmark.config.Ts(2:end)' * 1e6;
    dwell_us = diff(benchmark.config.Ts(:)) * 1e6;
    published_start_us = benchmark.published_boundary_us(1:end-1)';
    published_end_us = benchmark.published_boundary_us(2:end)';
    start_correction_us = start_us - published_start_us;
    end_correction_us = end_us - published_end_us;
    orbit_start = model.linearization.orbit_states(:, 1:end-1)';
    orbit_end = model.linearization.orbit_states(:, 2:end)';
    reference_table = table(interval, dynamics_index, published_mode, ...
        start_us, end_us, dwell_us, published_start_us, published_end_us, ...
        start_correction_us, end_correction_us, orbit_start(:, 1), ...
        orbit_start(:, 2), orbit_start(:, 3), orbit_end(:, 1), ...
        orbit_end(:, 2), orbit_end(:, 3), ...
        'VariableNames', {'interval', 'dynamics_index', 'published_mode', ...
        'start_us', 'end_us', 'dwell_us', 'published_start_us', ...
        'published_end_us', 'start_correction_us', 'end_correction_us', ...
        'start_vc1_v', 'start_vc2_v', 'start_il_a', 'end_vc1_v', ...
        'end_vc2_v', 'end_il_a'});
    writetable(reference_table, fullfile(paths.results, ...
        'reference_schedule_orbit.csv'));

    write_jacobian_table(fullfile(paths.results, 'jacobian_checks.csv'), ...
        model.linearization.Phi, model.Phi_fd, model.linearization.Gamma, model.Gamma_fd);
    writetable(table(model.perturbation_sizes, model.normalized_residual, model.fitted_residual, ...
        'VariableNames', {'perturbation_sizes', 'normalized_residual', 'fitted_residual'}), ...
        fullfile(paths.results, 'linearization_residual.csv'));

    cycles = (0:(size(response.conditioned_states, 2) - 1))';
    beta_rows = [response.conditioning_beta; nan];
    maximum_raw_offset_us = [max(abs(response.raw_offsets), [], 1)'; nan] * 1e6;
    maximum_applied_offset_us = ...
        [max(abs(response.applied_offsets), [], 1)'; nan] * 1e6;
    minimum_raw_dwell_us = [min(response.raw_dwell, [], 1)'; nan] * 1e6;
    minimum_applied_dwell_us = [min(response.applied_dwell, [], 1)'; nan] * 1e6;
    minimum_conservative_dwell_us = ...
        [min(response.conservative_dwell, [], 1)'; nan] * 1e6;
    response_table = table(cycles, response.conditioned_error, ...
        response.conservative_error, response.open_loop_error, beta_rows, ...
        maximum_raw_offset_us, maximum_applied_offset_us, ...
        minimum_raw_dwell_us, minimum_applied_dwell_us, ...
        minimum_conservative_dwell_us, ...
        response.conditioned_states(1, :)', response.conditioned_states(2, :)', ...
        response.conditioned_states(3, :)', response.conservative_states(1, :)', ...
        response.conservative_states(2, :)', response.conservative_states(3, :)', ...
        response.open_loop_states(1, :)', response.open_loop_states(2, :)', ...
        response.open_loop_states(3, :)', ...
        'VariableNames', {'cycle', 'conditioned_error', 'conservative_error', ...
        'open_loop_error', 'beta', 'maximum_raw_offset_us', ...
        'maximum_applied_offset_us', 'minimum_raw_dwell_us', ...
        'minimum_applied_dwell_us', 'minimum_conservative_dwell_us', ...
        'conditioned_vc1_v', 'conditioned_vc2_v', 'conditioned_il_a', ...
        'conservative_vc1_v', 'conservative_vc2_v', 'conservative_il_a', ...
        'open_vc1_v', 'open_vc2_v', 'open_il_a'});
    raw_offset_rows = [response.raw_offsets'; ...
        nan(1, size(response.raw_offsets, 1))];
    applied_offset_rows = [response.applied_offsets'; ...
        nan(1, size(response.applied_offsets, 1))];
    raw_dwell_rows = [response.raw_dwell'; ...
        nan(1, size(response.raw_dwell, 1))];
    applied_dwell_rows = [response.applied_dwell'; ...
        nan(1, size(response.applied_dwell, 1))];
    for index = 1:size(raw_offset_rows, 2)
        response_table.(sprintf('raw_offset_%d_us', index)) = ...
            raw_offset_rows(:, index) * 1e6;
        response_table.(sprintf('applied_offset_%d_us', index)) = ...
            applied_offset_rows(:, index) * 1e6;
    end
    for index = 1:size(raw_dwell_rows, 2)
        response_table.(sprintf('raw_dwell_%d_us', index)) = ...
            raw_dwell_rows(:, index) * 1e6;
        response_table.(sprintf('applied_dwell_%d_us', index)) = ...
            applied_dwell_rows(:, index) * 1e6;
    end
    writetable(response_table, fullfile(paths.results, ...
        'conditioned_control_response.csv'));

    results = struct();
    results.metrics = metrics;
    results.schedule = struct('Omega', benchmark.config.Omega, 'Ts', benchmark.config.Ts, ...
        'published_modes', benchmark.config.Omega - 1, ...
        'published_boundary_us', benchmark.published_boundary_us, ...
        'orbit_anchor', benchmark.config.orbit_anchor, ...
        'cycle_average_state', model.cycle_average_state);
    results.linearization = struct('Phi', model.linearization.Phi, ...
        'Gamma', model.linearization.Gamma, 'Phi_fd', model.Phi_fd, ...
        'Gamma_fd', model.Gamma_fd, 'state_fd_step', model.state_fd_step, ...
        'timing_fd_step', model.timing_fd_step, ...
        'perturbation_sizes', model.perturbation_sizes, ...
        'normalized_residual', model.normalized_residual, ...
        'fitted_residual', model.fitted_residual);
    controller.state_scale = benchmark.state_scale;
    controller.timing_scale = benchmark.timing_scale;
    results.controller = controller;
    results.invariant_raw_action_region = region;
    results.response = response;
    save(fullfile(paths.results, 'paper_results.mat'), 'results');
end

function write_jacobian_table(path, Phi, Phi_fd, Gamma, Gamma_fd)
    [phi_row, phi_column] = ind2sub(size(Phi), (1:numel(Phi))');
    [gamma_row, gamma_column] = ind2sub(size(Gamma), (1:numel(Gamma))');
    jacobian = [repmat("Phi", numel(Phi), 1); ...
        repmat("Gamma", numel(Gamma), 1)];
    row = [phi_row; gamma_row];
    column = [phi_column; gamma_column];
    analytical = [Phi(:); Gamma(:)];
    finite_difference = [Phi_fd(:); Gamma_fd(:)];
    absolute_error = abs(finite_difference - analytical);
    writetable(table(jacobian, row, column, analytical, ...
        finite_difference, absolute_error), path);
end

function write_metrics_tex(path, metrics)
    file = fopen(path, 'w');
    assert(file ~= -1, 'Could not write %s', path);
    cleanup = onCleanup(@() fclose(file));
    fprintf(file, '%% Generated by scripts/generate_results.m.\n');
    fprintf(file, '\\newcommand{\\NominalPeriodMicroseconds}{%.0f}\n', ...
        metrics.nominal_period_us);
    fprintf(file, '\\newcommand{\\NominalIntervalCount}{%d}\n', ...
        metrics.nominal_interval_count);
    fprintf(file, '\\newcommand{\\NominalClosureError}{%.3e}\n', ...
        metrics.nominal_closure_error_inf);
    fprintf(file, '\\newcommand{\\NominalMinimumDwell}{%.3f}\n', ...
        metrics.nominal_minimum_dwell_us);
    fprintf(file, '\\newcommand{\\BenchmarkDwellBound}{%.0f}\n', ...
        metrics.benchmark_design_dwell_bound_us);
    fprintf(file, '\\newcommand{\\AppliedScheduleDwellBound}{%.0f}\n', ...
        metrics.applied_schedule_dwell_bound_us);
    fprintf(file, '\\newcommand{\\MaximumBoundaryCorrection}{%.3f}\n', ...
        metrics.max_published_boundary_correction_us);
    fprintf(file, '\\newcommand{\\CycleAverageVCOne}{%.5f}\n', ...
        metrics.cycle_average_vc1_v);
    fprintf(file, '\\newcommand{\\CycleAverageVCTwo}{%.5f}\n', ...
        metrics.cycle_average_vc2_v);
    fprintf(file, '\\newcommand{\\CycleAverageIL}{%.5f}\n', ...
        metrics.cycle_average_il_a);
    fprintf(file, '\\newcommand{\\TimingScaleMicroseconds}{%.0f}\n', ...
        metrics.timing_scale_us);
    fprintf(file, '\\newcommand{\\PhiJacobianRelativeError}{%.3e}\n', ...
        metrics.phi_fd_relative_error);
    fprintf(file, '\\newcommand{\\GammaJacobianRelativeError}{%.3e}\n', ...
        metrics.gamma_fd_relative_error);
    fprintf(file, '\\newcommand{\\LinearizationResidualSlope}{%.3f}\n', ...
        metrics.residual_slope);
    fprintf(file, '\\newcommand{\\OpenLoopSpectralRadius}{%.6f}\n', ...
        metrics.open_loop_spectral_radius);
    fprintf(file, '\\newcommand{\\ConservativeSpectralRadius}{%.6f}\n', ...
        metrics.conservative_spectral_radius);
    fprintf(file, '\\newcommand{\\AggressiveSpectralRadius}{%.6f}\n', ...
        metrics.aggressive_spectral_radius);
    fprintf(file, '\\newcommand{\\InvariantRegionFacets}{%d}\n', ...
        metrics.invariant_region_facets);
    fprintf(file, '\\newcommand{\\InvariantRegionVertices}{%d}\n', ...
        metrics.invariant_region_vertices);
    fprintf(file, '\\newcommand{\\InvariantRegionVolume}{%.4f}\n', ...
        metrics.invariant_region_volume_physical);
    fprintf(file, '\\newcommand{\\InvariantRegionVCOneMin}{%.3f}\n', ...
        metrics.invariant_region_vc1_min_v);
    fprintf(file, '\\newcommand{\\InvariantRegionVCOneMax}{%.3f}\n', ...
        metrics.invariant_region_vc1_max_v);
    fprintf(file, '\\newcommand{\\InvariantRegionVCTwoMin}{%.3f}\n', ...
        metrics.invariant_region_vc2_min_v);
    fprintf(file, '\\newcommand{\\InvariantRegionVCTwoMax}{%.3f}\n', ...
        metrics.invariant_region_vc2_max_v);
    fprintf(file, '\\newcommand{\\InvariantRegionILMin}{%.3f}\n', ...
        metrics.invariant_region_il_min_a);
    fprintf(file, '\\newcommand{\\InvariantRegionILMax}{%.3f}\n', ...
        metrics.invariant_region_il_max_a);
    fprintf(file, '\\newcommand{\\InvariantRegionIterations}{%d}\n', ...
        metrics.invariant_region_iterations);
    fprintf(file, '\\newcommand{\\InvariantRegionImageDwellMargin}{%.3f}\n', ...
        metrics.invariant_region_image_dwell_margin_us);
    fprintf(file, '\\newcommand{\\FirstInvariantRegionCycle}{%d}\n', ...
        metrics.first_invariant_region_cycle);
    fprintf(file, '\\newcommand{\\LowerComparisonConditioningFactor}{%.1f}\n', ...
        metrics.lower_comparison_beta);
    fprintf(file, '\\newcommand{\\MiddleComparisonConditioningFactor}{%.1f}\n', ...
        metrics.middle_comparison_beta);
    fprintf(file, '\\newcommand{\\LowerComparisonRegionVolume}{%.4f}\n', ...
        metrics.lower_comparison_region_volume_physical);
    fprintf(file, '\\newcommand{\\MiddleComparisonRegionVolume}{%.4f}\n', ...
        metrics.middle_comparison_region_volume_physical);
    fprintf(file, '\\newcommand{\\LowerComparisonRegionVolumeRatio}{%.0f}\n', ...
        metrics.lower_comparison_region_volume_ratio);
    fprintf(file, '\\newcommand{\\MiddleComparisonRegionVolumeRatio}{%.0f}\n', ...
        metrics.middle_comparison_region_volume_ratio);
    fprintf(file, '\\newcommand{\\AggressiveInputWeight}{%.3g}\n', ...
        metrics.aggressive_input_weight);
    fprintf(file, '\\newcommand{\\ConservativeInputWeight}{%.3g}\n', ...
        metrics.conservative_input_weight);
    fprintf(file, '\\newcommand{\\InitialNormalizedError}{%.6f}\n', ...
        metrics.initial_normalized_error);
    fprintf(file, '\\newcommand{\\ConditionedFinalError}{%.3e}\n', ...
        metrics.conditioned_final_error);
    fprintf(file, '\\newcommand{\\ConservativeFinalError}{%.3e}\n', ...
        metrics.conservative_final_error);
    fprintf(file, '\\newcommand{\\OpenLoopFinalError}{%.6f}\n', ...
        metrics.open_loop_final_error);
    fprintf(file, '\\newcommand{\\ConditionedSettlingCycle}{%d}\n', ...
        metrics.conditioned_first_cycle_below_001);
    fprintf(file, '\\newcommand{\\ConservativeSettlingCycle}{%d}\n', ...
        metrics.conservative_first_cycle_below_001);
    fprintf(file, '\\newcommand{\\ConditionedCycleCount}{%d}\n', ...
        metrics.conditioned_cycles);
    fprintf(file, '\\newcommand{\\MinimumConditioningBeta}{%.6f}\n', ...
        metrics.minimum_conditioning_beta);
    fprintf(file, '\\newcommand{\\MaximumRawOffset}{%.3f}\n', ...
        metrics.maximum_raw_offset_us);
    fprintf(file, '\\newcommand{\\MaximumAppliedOffset}{%.3f}\n', ...
        metrics.maximum_applied_offset_us);
    fprintf(file, '\\newcommand{\\MinimumRawDwell}{%.3f}\n', ...
        metrics.minimum_raw_dwell_us);
    fprintf(file, '\\newcommand{\\MinimumAppliedDwell}{%.3f}\n', ...
        metrics.minimum_applied_dwell_us);
    fprintf(file, '\\newcommand{\\MinimumConservativeDwell}{%.3f}\n', ...
        metrics.minimum_conservative_dwell_us);
    fprintf(file, '\\newcommand{\\SimulationCycles}{%d}\n', ...
        metrics.simulation_cycles);
    fprintf(file, '\\newcommand{\\LongSimulationCycles}{%d}\n', ...
        metrics.long_simulation_cycles);
    fprintf(file, '\\newcommand{\\OpenLoopConvergenceCycle}{%d}\n', ...
        metrics.long_open_loop_convergence_cycle);
end

