// Copyright 2025 ITA (Instituto Tecnologico de Aeronautica). Licensed under the MIT license.
// Generated by simu2/+z_run/+Demos/z_create_lookup.m

#pragma once

#include "signal_controller.h"

void helper_set_dataset_from_alpha(DataSet *dataset, float alpha);
