@startuml

[*] --> IDLE

IDLE -> RUN_SIGNAL
IDLE -> RUN_HIGH
RUN_HIGH -> RUN_SIGNAL
RUN_HIGH -> IDLE
RUN_SIGNAL -> RUN_AND_READ
RUN_AND_READ -> SIGNAL_READING
SIGNAL_READING -> SIGNAL_CHANGED
SIGNAL_CHANGED -> RUN_SIGNAL
RUN_SIGNAL -> IDLE
IDLE --> [*]

@enduml
