function region = generate_feasible_regions(data)
%GENERATE_FEASIBLE_REGIONS Compute and plot fixed-beta dwell-feasible regions.
%   REGION = GENERATE_FEASIBLE_REGIONS(DATA) uses the linearized benchmark and
%   conditioned trajectory supplied by the main results pipeline.
%
%   GENERATE_FEASIBLE_REGIONS with no input reconstructs DATA from
%   results/paper_results.mat and regenerates only the region figure and vertex
%   CSV files. Run this form from the article root after generating the main
%   paper results at least once.

    article_dir = fileparts(fileparts(mfilename('fullpath')));
    if nargin == 0
        data = load_standalone_data(article_dir);
    end

    if ~isfolder(data.figures_dir), mkdir(data.figures_dir); end
    if ~isfolder(data.results_dir), mkdir(data.results_dir); end

    set(groot, 'defaultAxesFontName', 'Times New Roman');
    set(groot, 'defaultAxesFontSize', 9);
    set(groot, 'defaultLineLineWidth', 1.2);

    dwell_change_map = build_dwell_change_map( ...
        size(data.K_aggressive_normalized, 1));
    raw_region_A = dwell_change_map * data.K_aggressive_normalized;
    raw_region_b = (data.nominal_dwell ...
        - data.applied_schedule_dwell_bound) / data.timing_scale;
    [raw_admissible_region, invariant_raw_region, invariant_iterations] = ...
        compute_invariant_region(data.A_aggressive, raw_region_A, raw_region_b);

    invariant_vertices_normalized = invariant_raw_region.V;
    invariant_vertices_physical = ...
        (data.state_scale * invariant_vertices_normalized')';
    invariant_region_facet_count = size(invariant_raw_region.A, 1);
    invariant_region_vertex_count = size(invariant_vertices_normalized, 1);
    invariant_region_volume_physical = ...
        invariant_raw_region.volume() * abs(det(data.state_scale));
    invariant_region_ranges_physical = [ ...
        min(invariant_vertices_physical, [], 1); ...
        max(invariant_vertices_physical, [], 1)];
    minimum_vertex_dwell_margin = min(data.nominal_dwell ...
        - data.timing_scale * raw_region_A * invariant_vertices_normalized' ...
        - data.applied_schedule_dwell_bound, [], 'all');
    minimum_image_dwell_margin = min(data.nominal_dwell ...
        - data.timing_scale * raw_region_A * data.A_aggressive ...
            * invariant_vertices_normalized' ...
        - data.applied_schedule_dwell_bound, [], 'all');
    invariance_violation = max(invariant_raw_region.A ...
        * data.A_aggressive * invariant_vertices_normalized' ...
        - invariant_raw_region.b, [], 'all');
    origin_strict_margin = min(invariant_raw_region.b);
    regions_coincide = raw_admissible_region == invariant_raw_region;

    assert(~invariant_raw_region.isEmptySet() ...
        && invariant_raw_region.isFullDim() && invariant_raw_region.isBounded(), ...
        'The invariant raw-action region must be nonempty, full-dimensional, and bounded.');
    assert(origin_strict_margin > 0, ...
        'The origin is not in the strict interior of the invariant region.');
    assert(minimum_vertex_dwell_margin >= -1e-12, ...
        'An invariant-region vertex violates a raw dwell constraint.');
    assert(invariance_violation <= 1e-9 && minimum_image_dwell_margin >= -1e-12, ...
        'The raw closed-loop image is not contained in the invariant region.');
    assert(regions_coincide, ...
        'The maximal invariant subset does not equal the raw-action admissible region.');

    comparison_betas = [0.2, 0.5];
    comparison_feasible_regions = cell(size(comparison_betas));
    comparison_invariant_regions = cell(size(comparison_betas));
    comparison_invariant_iterations = zeros(size(comparison_betas));
    comparison_region_volumes_physical = zeros(size(comparison_betas));
    comparison_region_volume_ratios = zeros(size(comparison_betas));
    comparison_regions_are_invariant = false(size(comparison_betas));
    for index = 1:numel(comparison_betas)
        beta_value = comparison_betas(index);
        A_comparison = (1 - beta_value) * data.A_normalized ...
            + beta_value * data.A_aggressive;
        [comparison_feasible_regions{index}, ...
            comparison_invariant_regions{index}, ...
            comparison_invariant_iterations(index)] = ...
            compute_invariant_region(A_comparison, ...
            beta_value * raw_region_A, raw_region_b);
        comparison_region_volumes_physical(index) = ...
            comparison_feasible_regions{index}.volume() ...
            * abs(det(data.state_scale));
        comparison_region_volume_ratios(index) = ...
            comparison_region_volumes_physical(index) ...
            / invariant_region_volume_physical;
        comparison_regions_are_invariant(index) = ...
            comparison_feasible_regions{index} ...
            == comparison_invariant_regions{index};
        assert(abs(comparison_region_volume_ratios(index) ...
            - beta_value ^ -3) < 1e-9, ...
            'A fixed-beta feasible-region volume has unexpected scaling.');
    end

    conditioned_errors_normalized = data.state_scale \ ...
        (data.conditioned_states - data.orbit_anchor);
    conditioned_region_membership = false(size(data.conditioned_states, 2), 1);
    for index = 1:size(data.conditioned_states, 2)
        conditioned_region_membership(index) = ...
            invariant_raw_region.contains(conditioned_errors_normalized(:, index));
    end
    initial_state_in_invariant_region = conditioned_region_membership(1);
    first_invariant_region_cycle = ...
        find(conditioned_region_membership, 1) - 1;
    assert(~initial_state_in_invariant_region && first_invariant_region_cycle > 0, ...
        'The large-error trajectory does not enter the invariant region as expected.');

    region_metrics = struct( ...
        'facet_count', invariant_region_facet_count, ...
        'vertex_count', invariant_region_vertex_count, ...
        'volume_physical', invariant_region_volume_physical, ...
        'ranges_physical', invariant_region_ranges_physical, ...
        'minimum_vertex_dwell_margin', minimum_vertex_dwell_margin, ...
        'minimum_image_dwell_margin', minimum_image_dwell_margin, ...
        'invariance_violation', invariance_violation, ...
        'origin_strict_margin', origin_strict_margin, ...
        'comparison_volumes_physical', comparison_region_volumes_physical, ...
        'comparison_volume_ratios', comparison_region_volume_ratios, ...
        'initial_state_in_invariant_region', initial_state_in_invariant_region, ...
        'first_invariant_region_cycle', first_invariant_region_cycle);
    region = struct('raw_admissible', raw_admissible_region, ...
        'maximal_invariant', invariant_raw_region, ...
        'vertices_normalized', invariant_vertices_normalized, ...
        'vertices_physical', invariant_vertices_physical, ...
        'iterations', invariant_iterations, ...
        'regions_coincide', regions_coincide, ...
        'comparison_betas', comparison_betas, ...
        'comparison_feasible', {comparison_feasible_regions}, ...
        'comparison_maximal_invariant', {comparison_invariant_regions}, ...
        'comparison_invariant_iterations', comparison_invariant_iterations, ...
        'comparison_regions_are_invariant', comparison_regions_are_invariant, ...
        'metrics', region_metrics);

    write_region_vertices(data.results_dir, region, data.state_scale);
    figure_feasible_regions(data.figures_dir, region, data.state_scale, ...
        data.conditioned_states, data.orbit_anchor, first_invariant_region_cycle);

    fprintf(['Fixed-beta feasible regions: beta 1.000, volume %.9g V^2 A, ', ...
        'volume ratio 1.000000, invariant %d\n'], ...
        invariant_region_volume_physical, regions_coincide);
    for index = 1:numel(comparison_betas)
        fprintf(['Fixed-beta feasible regions: beta %.3f, volume %.9g V^2 A, ', ...
            'volume ratio %.6f, invariant %d\n'], comparison_betas(index), ...
            comparison_region_volumes_physical(index), ...
            comparison_region_volume_ratios(index), ...
            comparison_regions_are_invariant(index));
    end
end

function data = load_standalone_data(article_dir)
    mat_path = fullfile(article_dir, 'results', 'paper_results.mat');
    assert(isfile(mat_path), ...
        ['Standalone region generation requires results/paper_results.mat. ', ...
        'Run task figures first.']);
    saved = load(mat_path, 'results');
    results = saved.results;

    state_scale = results.controller.state_scale;
    timing_scale = results.controller.timing_scale;
    A_normalized = state_scale \ results.linearization.Phi * state_scale;
    B_normalized = state_scale \ results.linearization.Gamma * timing_scale;
    K_aggressive_normalized = results.controller.K_aggressive_normalized;

    data = struct( ...
        'A_normalized', A_normalized, ...
        'A_aggressive', A_normalized ...
            - B_normalized * K_aggressive_normalized, ...
        'nominal_dwell', diff(results.schedule.Ts(:)), ...
        'applied_schedule_dwell_bound', ...
            results.metrics.applied_schedule_dwell_bound_us * 1e-6, ...
        'timing_scale', timing_scale, ...
        'state_scale', state_scale, ...
        'K_aggressive_normalized', K_aggressive_normalized, ...
        'conditioned_states', results.response.conditioned_states, ...
        'orbit_anchor', results.schedule.orbit_anchor, ...
        'figures_dir', fullfile(article_dir, 'latex', 'figures'), ...
        'results_dir', fullfile(article_dir, 'results'));
end

function dwell_change_map = build_dwell_change_map(action_count)
    dwell_change_map = zeros(action_count + 1, action_count);
    dwell_change_map(1, 1) = 1;
    for interval = 2:action_count
        dwell_change_map(interval, interval - 1) = -1;
        dwell_change_map(interval, interval) = 1;
    end
    dwell_change_map(end, end) = -1;
end

function [admissible_region, invariant_region, iterations] = ...
        compute_invariant_region(closed_loop, region_A, region_b)
    assert(exist('Polyhedron', 'class') == 8, ...
        'MPT3 is required for the feasible-region computation.');
    row_norms = vecnorm(region_A, 2, 2);
    assert(all(row_norms > 0), ...
        'A raw-action dwell constraint has a zero normal.');
    admissible_region = Polyhedron(region_A ./ row_norms, ...
        region_b ./ row_norms);
    admissible_region.minHRep();

    invariant_region = admissible_region;
    iterations = 0;
    while true
        iterations = iterations + 1;
        preimage = Polyhedron(invariant_region.A * closed_loop, ...
            invariant_region.b);
        candidate = intersect(invariant_region, preimage);
        candidate.minHRep();
        if candidate == invariant_region
            invariant_region = candidate;
            break;
        end
        invariant_region = candidate;
        assert(iterations < 1000, ...
            'Invariant-region iteration did not converge in 1000 steps.');
    end
end

function write_region_vertices(results_dir, region, state_scale)
    region_vertices = array2table(region.vertices_physical, ...
        'VariableNames', {'error_vc1_v', 'error_vc2_v', 'error_il_a'});
    writetable(region_vertices, fullfile(results_dir, ...
        'invariant_raw_action_region_vertices.csv'));
    for index = 1:numel(region.comparison_betas)
        comparison_vertices_physical = ...
            (state_scale * region.comparison_feasible{index}.V')';
        comparison_vertices = array2table(comparison_vertices_physical, ...
            'VariableNames', {'error_vc1_v', 'error_vc2_v', 'error_il_a'});
        beta_label = strrep(sprintf('%.1f', region.comparison_betas(index)), ...
            '.', '_');
        writetable(comparison_vertices, fullfile(results_dir, sprintf( ...
            'fixed_beta_%s_feasible_region_vertices.csv', beta_label)));
    end
end

function figure_feasible_regions(figures_dir, region, state_scale, ...
        conditioned_states, anchor, first_entry_cycle)
    colors = [0.00, 0.35, 0.70; 0.90, 0.55, 0.10; ...
        0.25, 0.60, 0.30; 0.75, 0.20, 0.15; ...
        0.20, 0.20, 0.20; 0.95, 0.75, 0.10];
    inner_vertices = (state_scale * region.maximal_invariant.V')';
    middle_vertices = (state_scale * region.comparison_feasible{2}.V')';
    outer_vertices = (state_scale * region.comparison_feasible{1}.V')';
    inner_region = Polyhedron('V', inner_vertices);
    middle_region = Polyhedron('V', middle_vertices);
    outer_region = Polyhedron('V', outer_vertices);
    errors = conditioned_states - anchor;
    shown_cycles = 0:min(10, size(errors, 2) - 1);
    shown_errors = errors(:, shown_cycles + 1);
    inside_inner = false(size(shown_cycles));
    inside_middle = false(size(shown_cycles));
    inside_outer = false(size(shown_cycles));
    for index = 1:numel(shown_cycles)
        normalized_error = state_scale \ shown_errors(:, index);
        inside_inner(index) = region.maximal_invariant.contains(normalized_error);
        inside_middle(index) = region.comparison_feasible{2}.contains(normalized_error);
        inside_outer(index) = region.comparison_feasible{1}.contains(normalized_error);
    end
    middle_only = inside_middle & ~inside_inner;
    outer_only = inside_outer & ~inside_middle;
    outside_outer = ~inside_outer;
    entry_index = first_entry_cycle + 1;

    fig = figure('Visible', 'off', 'Position', [100, 100, 980, 650]);
    layout = tiledlayout(2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

    nexttile;
    outer_handles = plot(outer_region, 'color', colors(3, :), ...
        'alpha', 0.08, 'linewidth', 1.0);
    hold on;
    middle_handles = plot(middle_region, 'color', colors(2, :), ...
        'alpha', 0.14, 'linewidth', 1.0);
    inner_handles = plot(inner_region, 'color', colors(1, :), ...
        'alpha', 0.28, 'linewidth', 1.0);
    plot3(shown_errors(1, :), shown_errors(2, :), shown_errors(3, :), ...
        '-', 'Color', colors(5, :), 'HandleVisibility', 'off');
    plot3(shown_errors(1, outside_outer), ...
        shown_errors(2, outside_outer), shown_errors(3, outside_outer), ...
        'o', 'Color', colors(4, :), 'MarkerFaceColor', 'w', 'MarkerSize', 4, ...
        'HandleVisibility', 'off');
    plot3(shown_errors(1, outer_only), shown_errors(2, outer_only), ...
        shown_errors(3, outer_only), 'o', 'Color', colors(3, :), ...
        'MarkerFaceColor', 'w', 'MarkerSize', 4, 'HandleVisibility', 'off');
    plot3(shown_errors(1, middle_only), shown_errors(2, middle_only), ...
        shown_errors(3, middle_only), 'o', 'Color', colors(2, :), ...
        'MarkerFaceColor', 'w', 'MarkerSize', 4, 'HandleVisibility', 'off');
    plot3(shown_errors(1, inside_inner), ...
        shown_errors(2, inside_inner), shown_errors(3, inside_inner), ...
        'o', 'Color', colors(1, :), 'MarkerFaceColor', 'w', 'MarkerSize', 4);
    plot3(errors(1, 1), errors(2, 1), errors(3, 1), 'ks', ...
        'MarkerFaceColor', 'k', 'MarkerSize', 6, 'HandleVisibility', 'off');
    plot3(errors(1, entry_index), errors(2, entry_index), ...
        errors(3, entry_index), 'kd', 'MarkerFaceColor', colors(6, :), ...
        'MarkerSize', 7, 'HandleVisibility', 'off');
    plot3(0, 0, 0, 'kp', 'MarkerFaceColor', colors(1, :), ...
        'MarkerSize', 9, 'HandleVisibility', 'off');
    text(errors(1, 1), errors(2, 1), errors(3, 1), '  k=0');
    text(errors(1, entry_index), errors(2, entry_index), ...
        errors(3, entry_index), sprintf('  k=%d', first_entry_cycle));
    text(0, 0, 0, '  origin');
    xlabel('$e_{v_{C_1}}$ (V)', 'Interpreter', 'latex');
    ylabel('$e_{v_{C_2}}$ (V)', 'Interpreter', 'latex');
    zlabel('$e_{i_L}$ (A)', 'Interpreter', 'latex');
    title('(a) Three-dimensional regions', 'FontWeight', 'normal');
    legend([outer_handles(1), middle_handles(1), inner_handles(1)], ...
        {sprintf('Fixed $\\beta=%.1f$', region.comparison_betas(1)), ...
        sprintf('Fixed $\\beta=%.1f$', region.comparison_betas(2)), ...
        'Raw action, $\beta=1$'}, ...
        'Interpreter', 'latex', 'Location', 'best');
    grid on;
    axis padded;
    view(42, 24);

    projection_pairs = [1, 2; 1, 3; 2, 3];
    projection_labels = {{'$e_{v_{C_1}}$ (V)', '$e_{v_{C_2}}$ (V)'}, ...
        {'$e_{v_{C_1}}$ (V)', '$e_{i_L}$ (A)'}, ...
        {'$e_{v_{C_2}}$ (V)', '$e_{i_L}$ (A)'}};
    projection_titles = {'(b) Voltage-plane projection', ...
        '(c) First voltage-current projection', ...
        '(d) Second voltage-current projection'};
    for projection = 1:3
        nexttile;
        plot_region_projection(inner_vertices, middle_vertices, outer_vertices, ...
            shown_errors, inside_inner, middle_only, outer_only, outside_outer, ...
            projection_pairs(projection, :), ...
            projection_labels{projection}, projection_titles{projection}, ...
            first_entry_cycle, colors);
    end

    title(layout, 'Fixed-factor dwell-feasible regions', ...
        'FontWeight', 'normal');
    exportgraphics(fig, fullfile(figures_dir, ...
        'invariant_raw_action_region.pdf'), 'ContentType', 'vector');
    close(fig);
end

function plot_region_projection(inner_vertices, middle_vertices, ...
        outer_vertices, errors, inside_inner, middle_only, outer_only, ...
        outside_outer, coordinates, labels, panel_title, first_entry_cycle, colors)
    outer_projection = outer_vertices(:, coordinates);
    outer_boundary = convhull(outer_projection(:, 1), outer_projection(:, 2));
    fill(outer_projection(outer_boundary, 1), ...
        outer_projection(outer_boundary, 2), colors(3, :), ...
        'FaceAlpha', 0.12, 'EdgeColor', colors(3, :), 'LineWidth', 1.2);
    hold on;
    middle_projection = middle_vertices(:, coordinates);
    middle_boundary = convhull(middle_projection(:, 1), middle_projection(:, 2));
    fill(middle_projection(middle_boundary, 1), ...
        middle_projection(middle_boundary, 2), colors(2, :), ...
        'FaceAlpha', 0.17, 'EdgeColor', colors(2, :), 'LineWidth', 1.2);
    inner_projection = inner_vertices(:, coordinates);
    inner_boundary = convhull(inner_projection(:, 1), inner_projection(:, 2));
    fill(inner_projection(inner_boundary, 1), ...
        inner_projection(inner_boundary, 2), colors(1, :), ...
        'FaceAlpha', 0.24, 'EdgeColor', colors(1, :), 'LineWidth', 1.2);
    plot(errors(coordinates(1), :), errors(coordinates(2), :), '-', ...
        'Color', colors(5, :));
    plot(errors(coordinates(1), outside_outer), ...
        errors(coordinates(2), outside_outer), 'o', 'Color', colors(4, :), ...
        'MarkerFaceColor', 'w', 'MarkerSize', 4);
    plot(errors(coordinates(1), outer_only), ...
        errors(coordinates(2), outer_only), 'o', 'Color', colors(3, :), ...
        'MarkerFaceColor', 'w', 'MarkerSize', 4);
    plot(errors(coordinates(1), middle_only), ...
        errors(coordinates(2), middle_only), 'o', 'Color', colors(2, :), ...
        'MarkerFaceColor', 'w', 'MarkerSize', 4);
    plot(errors(coordinates(1), inside_inner), ...
        errors(coordinates(2), inside_inner), 'o', 'Color', colors(1, :), ...
        'MarkerFaceColor', 'w', 'MarkerSize', 4);
    plot(errors(coordinates(1), 1), errors(coordinates(2), 1), 'ks', ...
        'MarkerFaceColor', 'k', 'MarkerSize', 6);
    entry_index = first_entry_cycle + 1;
    plot(errors(coordinates(1), entry_index), ...
        errors(coordinates(2), entry_index), 'kd', ...
        'MarkerFaceColor', colors(6, :), 'MarkerSize', 7);
    plot(0, 0, 'kp', 'MarkerFaceColor', colors(1, :), 'MarkerSize', 9);
    text(errors(coordinates(1), 1), errors(coordinates(2), 1), '  k=0');
    text(errors(coordinates(1), entry_index), ...
        errors(coordinates(2), entry_index), ...
        sprintf('  k=%d', first_entry_cycle));
    xlabel(labels{1}, 'Interpreter', 'latex');
    ylabel(labels{2}, 'Interpreter', 'latex');
    title(panel_title, 'FontWeight', 'normal');
    axis padded;
    grid on;
end
